### ISSUE TITLE
翻译进度

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/fsfs-zh#14]
### Contents

- [x] Foreword to the Third Edition 
- [x] Foreword to the First Edition
- [x] Preface 
- Part I: The GNU Project and Free Software
   - [x]  What Is Free Software? 
   - [x] The GNU Project 
   - [x] The Initial Announcement of the GNU Operating System 
   - [x] Free Software Is Even More Important Now .
   - [x] Why Schools Should Exclusively Use Free Software 
   - [x] Measures Governments Can Use to Promote Free Software
   - [x] Why Free Software Needs Free Documentation
   - [x] Selling Free Software
   - [x] Free Hardware and Free Hardware Designs 
   - [x] Applying the Free Software Criteria 
- Part II: What’s in a Name?
   - [x] What’s in a Name? .
   - [x] Linux and the GNU System 
   - [x] Categories of Free and Nonfree Software 
   - [x] Why Open Source Misses the Point of Free Software 
   - [x] Did You Say “Intellectual Property”? It’s a Seductive Mirage 
   - [x] Why Call It the Swindle? 
   - [x] Words to Avoid (or Use with Care) Because They Are Loaded or Confusing
- Part III: Copyright and Injustice
   - [x] The Right to Read
   - [x] Misinterpreting Copyright—A Series of Errors 
   - [x] Science Must Push Copyright Aside
   - [x] Copyright vs. Community in the Age of Computer Networks 
- Part IV: Software Patents: Danger to Programmers
   - [x] Software Patents and Literary Patents 
   - [x] The Danger of Software Patents 
   - [x] Giving the Software Field Protection from Patents 
- Part V: Free Software Licensing
   - [x] Introduction to the Licenses 
   - [x] How to Choose a License for Your Own Work
   - [x] The X Window System Trap 
   - [x] Programs Must Not Limit the Freedom to Run Them
   - [x] What Is Copyleft? 
   - [x] Why Copyleft?
   - [x] Copyleft: Pragmatic Idealism
   - [x] The GNU General Public License
   - [x] Why Upgrade to GPLv3
   - [x] The GNU Lesser General Public License
   - [x] GNU Free Documentation License 
   - [x] On Selling Exceptions to the GNU GPL
- Part VI: Traps and Challenges
   - [x] Can You Trust Your Computer? .
   - [x] The JavaScript Trap
   - [x] Releasing Free Software If You Work at a University 
   - [x] Nonfree DRM’d Games on GNU/Linux: Good or Bad? 
   - [x] The Danger of E-Books 
   - [x] E-books Must Increase Our Freedom, Not Decrease It 
   - [x] Who Does That Server Really Serve? 
- Part VII: Value Community and Your Freedom
   - [x] Avoiding Ruinous Compromises 
   - [x] Overcoming Social Inertia 
   - [x] Freedom or Power?
   - [x] Imperfection Is Not the Same as Oppression 
   - [x] How Much Surveillance Can Democracy Withstand? 
- [x] A Note on Software 
- [x] B: Translations of “Free Software” and “Gratis Software”
- [x] C: The Free Software Song

**Comment by nadebula** [comment]
The Part IV is already completed.

**Comment by nadebula** [comment]
Two shorter essays in Part III translated.

**Comment by nadebula** [comment]
Part III finished on Jul 1st 2016, pull request ASAP.

**Comment by biergaizi** [comment]
I'm working on Why Upgrade to GPLv3, to avoid conflicts, please do not translate it.

**Comment by biergaizi** [comment]
Why Upgrade to GPLv3 is translated and PR is sent (#54).

**Comment by biergaizi** [comment]
programs-must-not-limit-freedom-to-run.md is translated and PR is sent (#55).

**Comment by nadebula** [comment]
"Why Call It the Swindle" completed; PR submitted

**Comment by nadebula** [comment]
"Intellectual Property" completed; PR submitted

**Comment by nadebula** [comment]
"Applying the Free Software Criteria" and "The X Window System Trap" updated; PR submitted

**Comment by nadebula** [comment]
"Categories of Free and Nonfree Software" finished

**Comment by nadebula** [comment]
THE FULL CIRCLE
