### ISSUE TITLE
页内的参见信息不对

### ISSUE THREAD

**Issue by wxy** [beijinglug/fsfs-zh#147]
https://github.com/beijinglug/fsfs-zh/blob/master/docs/free-sw.md 中的四个参见链接中，除了3，其它几个都有问题。

**Comment by tonghuix** [comment]
Github 对 Markdown 语法支持比较少，这种脚注语法需要专门扩展。因为生成的 HTML 和 PDF 是正常的，所以也就没考虑用其他方式。
