### ISSUE TITLE
麻烦修一下错字

### ISSUE THREAD

**Issue by IFRFSX** [beijinglug/fsfs-zh#160]
在 GNU工程的初始公告 里面 把“从来都不是目的”写成了“从来都是不是目的”，还有其他极个别地方能看到把“不是”，翻译成“是不是”的错误。
还有，你们翻译《计算机网络时代的版权与社区之争》的时候不小心把“我不反对税收”写成了“我不分享税收”。
我看出来了这些小错误，麻烦修正一下。

**Comment by tonghuix** [comment]
谢谢指正！
