### ISSUE TITLE
生成的PDF档中有很多“\newpage”

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#162]

**Comment by mytbk** [comment]
还真的是这样。
当初加\newpage是为了LaTeX生成的时候在某些地方开新页，但是我一直觉得这不是一个好的做法。

**Comment by mytbk** [comment]
我用Arch的pandoc,发现\newpage被翻译成了\textbackslash{}newpage

**Comment by tonghuix** [comment]
确实，新版本的 pandoc 并没有很好的解决 ```\newpage``` 标签。

**Comment by mytbk** [comment]
刚刚推了个新的pdf模板:
https://github.com/beijinglug/fsfs-zh/tree/kill-newpage

**Comment by mytbk** [comment]
在一个Ubuntu 16.04的机器上生成了一份pdf，感觉还行：
https://wehack.space/vimacs/fsfs-zh.pdf

**Comment by mytbk** [comment]
在仔细对比了一下，发现这么改了之后，每一节的编号没了。

**Comment by tonghuix** [comment]
我觉得编号没有是件好事！！因为原书也没有！

**Comment by mytbk** [comment]
我先把这个修改合进master并发个release，看一下是什么效果，其他的问题以后再修复。

**Comment by tonghuix** [comment]
@mytbk 我在 Debian Buster 下面生成的新 PDF 已经传到 release 里面了。目前编号也出现了。

关于如何生成原书的编号，咱们可能还需要再研究一下。
