### ISSUE TITLE
一些排版问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#164]
注意到：
## 4.3 保护软件领域免受专利困扰：第202页，PDF中220页

> Copyright © 2012, 2013 自由软件基金会，本文的一个版本最初以标题 “Let’s Limit the Effect of Software Patents, Since We Can’t Eliminate Them” 发表于《连线》杂志 Wired 网站（Wired，2012 年 11 月 1 日。http://wired.com/opinion/2012/11/richard-stallman-software-patents/）。该版本于 2012 年发表于 http://gnu.org

中的
> http://wired.com/opinion/2012/11/richard-stallman-software-patents/

超出页面了
## 5.11.14 GNU 自由文档许可证 GNU Free Documentation License：第273页，PDF中的第291页

> Copyright (C)  year  your name.  
> Permission is granted to copy, distribute and/or modify this document 
> under the terms of the GNU Free Documentation License, Version 1.3 or  
> any later version published by the Free Software Foundation; with no 
> Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. 
> A copy of the license is included in the section entitled "GNU Free 
> Documentation License"".

也超出了范围

**Comment by tonghuix** [comment]
我记得之前貌似是用手动强行换行的方式修复了，怎么现在又出现了。

**Comment by tonghuix** [comment]
感谢订正，新的 commit 已经修复了这两个问题。

查了一下，这两个是之前漏掉没有修复的。
