### ISSUE TITLE
几个表述问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#165]
1.1.1 自由软件的定义：
## 注意到：

> 修改软件的一个重要方法是合并可用的自由子程序或模块。如果一个程序的许可证让你不能将一个合理授权发布的现有模块融合进来——例如要求你成为你修改过代码的版权所有者，那么该许可证过于严苛以致不能被视为自由的

中的
> 例如要求你成为你修改过代码的版权所有者

我认为这里的表述是不准确的。
[https://www.gnu.org/philosophy/free-sw.html](https://www.gnu.org/philosophy/free-sw.html)中这一段是这样的：
>  倘若要修改某个程序，一种很重要的方法就是从别的程序中拿来现成的函数，或模块来使用。如果某个程序的许可证中禁止你使用其他合理授权的软件的代码来修改该程序—比如，如果某个程序的许可证要求你只能使用你拥有版权的代码—那么这个程序的许可证将不被视为自由软件许可证。 

表述为：
> 如果某个程序的许可证要求你只能使用你拥有版权的代码

## 另一处：

> 我们无法将这些可能的情形一一列出。如果一个基于合同的许可证以不同于基于版权许可证的方式限制了用户，此处也没有表明其为合法，那么我们就需要考察这个许可证，并且很可能会将之视为非自由的。

我认为
> 此处也没有表明其为合法

也是不妥的，
[https://www.gnu.org/philosophy/free-sw.html](https://www.gnu.org/philosophy/free-sw.html)中这一段是这样的：
>  很遗憾，我们无法列出所有可能的意外情况。如果一份基于合同的许可证对用户做出了一些额外限制，并且这些限制是不可能包含在一份基于版权的许可证中的，那么我们就需要再三考虑它是否可以被视作自由许可证。很多情况下，这些许可证都是非自由的。 

表述为：
> 并且这些限制是不可能包含在一份基于版权的许可证中的

## 又另一处

>  最后，这些有关自由软件的标准需要谨慎的解读。判断一个软件许可证是否是自由软件许可证，标准就是看它是否符合自由软件精神以及用语是否精确。如果一个许可证包含了不合理的限制，即便是此文中我们没有预料到的问题，我们也会拒绝它。有些时候一个许可证会带来新的问题和思考，这需要我们与律师咨询以后，共同思考和研判。我们最终得出结论以后，将会更新这份标准以使其能更容易体现特定的许可证是否符合标准。

我认为
> 用语是否精确

的表述是模糊的
[https://www.gnu.org/philosophy/free-sw.html](https://www.gnu.org/philosophy/free-sw.html)中这一段是这样的：
>  最后请注意，在实践中，本文中提及的各种关于自由软件的界定标准都需要仔细思考后再做出解释。在决定一个软件许可证是否是自由软件的时候，我们会仔细查看该许可证的内涵和行文是否符合本文中涉及的原则，由此决定许可证是否为自由软件许可证。如果许可证中包含了一些不合理的限制，哪怕这些限制没有在本文中提及，我们也会拒绝承认它是自由的。有时候，某个许可证可能会引起一场大讨论，甚至需要专业律师参与。这时候，我们往往需要仔细定夺之后才能给出结论。遇到这样的许可证，在做出结论之后，我们很可能会更新本文，把之前没有考虑到的因素添加进来。 

其表述是这样的：
> 行文是否符合本文中涉及的原则

**Comment by tonghuix** [comment]
GNU 官网中此文的中文翻译很多意译的部分，虽然不能说不准确。但是我们当时认为首先是尽量少的意译，尽力按原文思想直接翻译，尽力表达 RMS 最想的直接思想，给读者自己更多解读的空间。

还是尽量看原文来讨论吧，我把你有异议的部分原文找出来了：

第一处的原文：

> for instance, if it requires you to be the copyright holder of any code you add

第二处的原文：

> If a contract-based license restricts the user in an unusual way that copyright-based licenses cannot, and which isn't mentioned here as legitimate, we will have to think about it, and we will probably conclude it is nonfree.

第三处原文：

> To decide whether a specific software license qualifies as a free software license, we judge it based on these criteria to determine whether it fits their spirit as well as the precise words.

**Comment by Hagb** [comment]
@tonghuix 看这本书这几处的时候，我感觉说得有点奇怪。

**Comment by tonghuix** [comment]
@Hagb 现在看当时翻译确实有点怪，但是又要如何平衡原意和意译呢。。。

**Comment by Hagb** [comment]
@tonghuix 
## 1
我认为，第一句应译成“例如要求**你是你所添加进的代码**的版权所有者”
>  for instance, if it **requires you to be** the copyright holder of **any code you add**

request sb to do sth：要求某人……；"requires you to be" 我觉得应该是指“要求你是”而不是“要求你成为”
## 2
我认为，第二句话可能更应该表述为“(人们)也无法表明**其在许可证中**可以合法存在”
> If a contract-based license restricts the user in an unusual way that copyright-based licenses cannot, and which isn't mentioned here as legitimate, we will have to think about it, and we will probably conclude it is nonfree.

which我认为是引导了定语从句“ isn't mentioned here as legitimate”，修饰前面的“copyright-based licenses”；mentioned大概是表被动，是否加一个动作者上去会好一些？
## 3
我认为，译成“用语是否**确切**”更好
> To decide whether a specific software license qualifies as a free software license, we judge it based on these criteria to determine whether it fits their spirit as well as the precise words.

“precise”有“确切”的意思

**Comment by tonghuix** [comment]
我觉得 1 和 3 都可以按你想的来。要不你直接提 PR 如何？

关于 2，代指 自由 可能不太合适吧，咱们再想想。
