### ISSUE TITLE
关于反馈到GNU

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#166]
README中提到，“我们正在努力将翻译成果反馈到 GNU 官网”，进行地怎么样了，需要怎么做？

**Comment by tonghuix** [comment]
这里有介绍，但是 GNU CTT 基本已经沉寂，一直无法顺利推进
https://www.gnu.org/server/standards/translations/zh-cn/workflow.zh-cn.html

**Comment by tonghuix** [comment]
GNU 官网将原文按段落拆成 po 文件里的条目，所以需要对应条目翻译，其实工作量很繁复。

@Hagb 如果有兴趣可以尝试用 poedit 这样的 po 文件编辑器尝试编辑试试看。

**Comment by Hagb** [comment]
@tonghuix 我可以在有空的时候（事实上可能没多少空，学业繁重）对这本书的译文进行编辑，但是我注意到，GNU已经有的一些译文在本书有不同的版本。

**Comment by tonghuix** [comment]
我认为是择优而用，如果那边的译文更好就保留，如果这里的译文更好则用这边的。重点是两边要同步和一致。

**Comment by Hagb** [comment]
@tonghuix 其实我觉得不容易选择，各有优劣吧

**Comment by Hagb** [comment]
@tonghuix 我最近正在翻译一篇文章（因为课余时间不多，这可能花费几个星期），等我完成这项工作之后我就准备将这边的成果同步过去。

**Comment by tonghuix** [comment]
好的，辛苦你啦！

**Comment by Hagb** [comment]
@tonghuix 不辛苦……进展会有点慢……时间不多，而且外语也不是很好

**Comment by Hagb** [comment]
@tonghuix 我想知道……fsfs3放在GNU版本库的什么地方？我没找到。它是分散在各篇文章里的还是集中在一个目录的？

**Comment by tonghuix** [comment]
分散在各处。。。你需要按标题搜索，超级麻烦！

**Comment by mytbk** [comment]
@Hagb 我找到的一份源文件是 http://www.gnu.org/doc/fsfs3-hardcover.tar.gz 
是在GNU的商店的页面里面找到的 https://shop.fsf.org/books-docs/free-software-free-society-selected-essays-richard-m-stallman-3rd-edition

**Comment by tonghuix** [comment]
@mytbk 我觉得 @Hagb 的意思是回馈到 GNU 官网的时候，这些文章在 GNU 代码库的什么位置

**Comment by Hagb** [comment]
@tonghuix 是的。是这个意思。现在知道是分散的就行了。

**Comment by IFRFSX** [comment]
你们得考虑到一个严重的问题——GNU官方推荐的非官方翻译存在很严重的问题，比如把Copyleft翻译为“版权共产”，把“......不受反破解法影响”翻译为“......不受反破解法侵害”。
这。。太可怕了。

**Comment by Hagb** [comment]
@IFRFSX 版权共产 -_- ? RMS不是说不是共产主义者吗？

**Comment by Hagb** [comment]
@IFRFSX 感觉版权共产不错，比左版好

> “共产”是指由全体劳动者共同拥有生产资料，共同进行生产劳动，按照共同协议来分配产品

翻译成“版权所左”也可以……（保留了双关语的性质：与版权所右即版权所有的谐音相反）

**Comment by tonghuix** [comment]
额貌似 OT 的有点严重啊，我强烈建议另开 issue 讨论关于 Copyleft 如何翻译的问题。

记得一个 issue 只讨论一个中心议题，可以方便检索和查询。

**Comment by biergaizi** [comment]
注意不要“劫持”讨论主题。

**Comment by Hagb** [comment]
@tonghuix 我看到您也在 CTT 中，您有没有和他们说过呢？

**Comment by Hagb** [comment]
@IFRFSX @tonghuix 看了你们的讨论……这样子吧，我这周就开始反馈到GNU。

**Comment by tonghuix** [comment]
因为有 #209 我就把这个关闭了
