### ISSUE TITLE
我想把附录A那幅代码图做成矢量图

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#171]
如题，我想把[doc/code.png](https://github.com/beijinglug/fsfs-zh/blob/master/docs/code.png)做成矢量图来替换掉原来的图片（尽管原文也是点阵图）

**Comment by tonghuix** [comment]
嘿嘿可以啊！这样也更好大家理解

**Comment by Hagb** [comment]
@tonghuix 那我干脆随便改成中文吧。今晚弄。

**Comment by tonghuix** [comment]
可以，别太“随便”。。哈哈

**Comment by Hagb** [comment]
@tonghuix不好意思。打错了。应是顺便

**Comment by Hagb** [comment]
已经搞定。close
