### ISSUE TITLE
关于附录B：“各国语言对自由软件和免费软件的翻译”的排版的一个问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#172]
排版上，为什么是以把文字做成图片的方式来处理呢？能否直接使用文字？

**Comment by tonghuix** [comment]
原文就直接用的图片。。。但我觉得这样最保险

**Comment by tonghuix** [comment]
我本人并没有研究过这个细节，主要是不知道 pandoc 对解析内嵌 PDF/矢量图 的markdown文件的效果如何，需要一些研究和实践。我相信工作量应该不大吧，因为原图的 PDF/矢量图 肯定能找到。

**Comment by Hagb** [comment]
@tonghuix 可以先试一试直接使用文字？不行就不这么干吧。

**Comment by tonghuix** [comment]
@Hagb 你先尝试一下，别着急发 PR

**Comment by Hagb** [comment]
@tonghuix 在学校没有环境和大块时间……得下周五了

**Comment by tonghuix** [comment]
没关系，不急
