### ISSUE TITLE
关于Copyleft的翻译

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#183]
现在我知道有一下几种译文（如果有别的译文，请补充）：
- 左版
- 版权属左
- 著佐权
- 版权所左
- 版权共产
- 版左
- 非独占性版权
- 版权共享

哪种会更好一些呢？

**Comment by heysion** [comment]
https://zh.wikipedia.org/wiki/Copyleft
版权共享 ？

**Comment by IFRFSX** [comment]
个人以为，著佐权或者左版比较好。。或者。。反向版权（我自己想出来的一个词汇）
但是，有一个很重要的事情是：绝不可以选择“版权共产”或者“版权共享”。
为什么呢？首先，copyleft是指你无论复制修改到什么程度，都不许更改许可证（除非许可证或者版权声明里面带有例外）。
所以，你可以私藏，这并不违反copyleft原则，而这本身不属于共产或者共享，自然不合适。
并且，非要说“共产”，那可能更接近以实用主义，更好的开发模式为原则的“开源软件”，并且还不完全一样。
版权属/所 左，这个词汇有点别扭，不太好理解，故不考虑。
为什么我会想出来“反向版权”呢？因为我发现Copyleft式的版权是为了保护自由，而普通的版权一般为对自由有限制性的。
左版，著佐权，反向版权，这三个翻译还望组织上斟酌一下。

请看 [https://getgnulinux.org/linux/linux_faq/] 页面的一段话：
{
[FAQ]
GNU/Linux 是共产主义的一种形式吗？
“每一样东西都必须是自由的”，“没有一个人拥有任何东西”听起来有点不可思议。GNU/Linux 以及 GPL 许可协议是不是属于无政府主义或者共产主义？
GNU/Linux 与政治体系没有任何关系——持有任何政见的人都可以使用它。我们已经在我们的人们对自由软件有哪些误解一文中解释了这个问题。
}

最后，我来表明一下我的态度：
我在@tonghuix 的个人网站看到他建议用“开源”来取代“自由软件”词汇，从各方面来看，很抱歉，我认为这实在是不妥，不能苟同。
为什么呢？因为开放和自由不是一个概念啊。
我知道tonghuix先生的本意是好的，为了团结社区。但是我们不能用合并思想的方法来做到。
为什么呢？很简单——因为不一样。
自由软件的思想是尊重用户的自由，保证社区的团结和协作。开源的思想呢？就比较实用主义了。
本人曾经见过几个不具有自由精神的开源支持者，他们甚至都不认为厂商锁死设备而不让用户修改的行为是不好的，而这种锁死行为正是和自由精神对立的。在这些人中，有人甚至公开反对GPL，认为“FSF不Copyleft也会有好多人来做贡献的”——甚至有一个人还故意用MIT这种宽松的License，说是担心“把贡献者吓跑”。从那以后我就逐渐明白了二者的区别——纯粹开源 的 思想（如果脱离的自由精神）就是希望吸引人来做贡献，让自己的软件更好，减轻自己的负担，而不很注重用户的自由。

正所谓“君子和而不同，小人同而不合”。即使侧重点不一样，两方阵营依然可以和平共处，一起合作，不妨碍什么。
我注重自由，你注重质量，这不是对立的精神，而是侧重点的不同。有这样的区别，如果能处理好双方的关系，不但不影响什么，相反还可以让人们有更多选择的余地，不至于导致意识形态的过度中心话。
反倒是专有软件阵营，为了一个圆角矩形的案件形状都能在法庭上斗得你死我活，足以证明了，同一个发展模式，思想的侧重点不一样并不会有什么隔阂，有时候甚至可以给人们更多的选择——喜欢和追求自由吗？请加入自由软件阵营。希望你的软件质量更好吗？请加入开源软件阵营。
两个阵营因为本是同根生，本来就应该是亲密的盟友关系。既然tonghuix先生您是FSF和GNOME的成员，那么可以考虑一下我的这个建议：你可以加第三个组织——开放源码促进会，为两边的如果两个阵营的人能因为您的努力而变得更加团结，那么您可能就会是自由世界有史以来的大功臣。
顺带一提，RMS大神写那篇《为什么开源漏掉了自由软件的要点》并非是攻击，而是不希望和开源阵营的人混为一谈。

以上信息，希望对贵组织有帮助。

**Comment by Hagb** [comment]
@IFRFSX  但是，“共产”和“共产主义”不是一回事啊。

**Comment by IFRFSX** [comment]
容易产生误会。
共产，我最近看到一个fuder在他的个人网站上喷GPL，提到谋篇蹩脚翻译中的“版权共产”，就开始偏激地扯出来什么linus他爸是gcd员之类的。。呵呵，所以为了保证不会和某主义联系到一起，还是不要带共产二字比较好哈。

**Comment by tonghuix** [comment]
> 我在@tonghuix 的个人网站看到他建议用“开源”来取代“自由软件”词汇

貌似我并没有在个人网站里说这种话吧，你是不是又过度解读了？

**Comment by tonghuix** [comment]
我搜遍了自己的网站，在这篇文章的开头 https://tonghuix.io/2018/02/open-source-20-anniversary/ 有这么一段：
> 1998 年的 2 月 5 日，一场小型聚会正在美国加州的 VA 研究中心举行，与会的人包括了 Eric Raymond、Larry Augustin 等人还有通过电话参与的 Jon “maddog” Hall。正是在这场会上，大家同意了 Christine Peterson 女士提出的用“开放源代码”（Open Source）一词来替代容易在英语人士中引起歧义的“自由软件”（Free Software）一词，而表达的是同样的软件和意思，却更方便理解更容易获取更多支持。从那一天开始，“开源”正式诞生，而今年二月正是开源运动发起二十周年！

@IFRFSX 请确认你的中文阅读理解能力达到了及格水平，如果你这两天高考，祝你高中榜眼！

**Comment by IFRFSX** [comment]
@tonghuix 
抱歉哈，昨天因为太着急，我打字的时没把话说准确——
“看到他建议用“开源”来取代“自由软件”词汇” =改==为=》“感觉他似乎更喜欢用开源这个词而不是自由软件”
“本来就应该是亲密的盟友关系” =改==为=》“应该成为盟友而不是敌人”

但我确实是不希望自由软件和开源软件合并，理由我已经说过了。
如果把软件自由运动比作一棵正在快速成长的树木，
自由软件和开源软件是主干和分支的关系。
没了主干，分支就会掉到土里，或者掉到河水里面随波逐流。
没了分支，光秃秃的主干的生命力会减少，收到的阳光也会变少。
两个团体大致就是这样的关系。

好了，回归正题——copyleft翻译！

我觉得，我想出来的“反向版权”这个词汇最精确的，因为大部分效果确实和普通的版权授权形式相反，虽然它们都是版权授权。。
您觉得呢？

**Comment by IFRFSX** [comment]
又想出来2个：
@tonghuix
@Hagb

版左
非独占性版权

**Comment by tonghuix** [comment]
@IFRFSX 还是过度解读啊，我并没有“更喜欢”或者“更偏爱”某个词嘛，虽然我平时用“开源”更多一些，也是照顾到受众和传播需要啊。我感觉你对自由软件和开源的理解还比较浅，有空的时候给你讲讲我的想法。

-----

关于 Copyleft 的翻译，我本人喜欢：**著佐权**（或***佐版***）、**非独占性版权**。著佐权有借取 left 的妙，而且佐根据在《说文解字》里的解释是```手相左助也。从￼、工。凡左之屬皆从左。則箇切〖注〗臣鉉等曰：今俗別作佐。```从这个意思上也能理解 Copyleft 正是辅佐自由软件成功的一个关键因素。

非独占性版权，就属于意译了，但这个意译却又足够准确。

**Comment by Hagb** [comment]
@tonghuix “版权所左”是我一个同学想到的，思路是和“版权所有”的谐音“版权所右”相对立。“著佐权”是比这个好，但是有一点是，会不会让人联想到著作权？

**Comment by tonghuix** [comment]
@Hagb 确实啊，著佐权的缺点就是很容易让人想到是著作权打错了。版权所左我也觉得挺好哈，你这么一解释也觉得这个创意很棒！

**Comment by IFRFSX** [comment]
@tonghuix 
说明一下，我对自由软件已经几乎完全理解了，但对开源只是比较理解。后来有个熟人告诉我，实用主义开源（不带自由的纯开源）和软件自由沾不上边的，在此之前我也知道。

不过，这种分歧也不影响什么，继续合作就好了。

————————
@Hagb 
我觉得你这个版权所左的翻译确实很有创意呢。

目前，我对这个词的理解是：我发布了作品，可以使用，复制或者修改（有的甚至可以商业性地做这些事情）。可是，我留下的许可证是不能更改或者替换的——除非许可证或者版权声明里面带有例外授权。

举例子：
比如GPLv2 or later version是可以用GPLv2或者v3来发布修改版的。
不带or later version 就是不可以升级到v3
LGPL可以ReLicense到同样或者更高版本的GPL。
AGPL是可以和GPL链接的。

**Comment by IFRFSX** [comment]
@tonghuix 
@Hagb 
“版权所左”是适合声明的词汇，而“左版”“反向版权”更适合做名词，望斟酌。

**Comment by Hagb** [comment]
@IFRFSX 没懂什么是适合声明的词汇

**Comment by tonghuix** [comment]
所以目前还是“左版”用的最多？

**Comment by tonghuix** [comment]
目前是确定 Copyleft 翻译成“左版”了对吧？如果定下来，我觉得可以和 GNU 上游把这个翻译统一起来。

**Comment by Hagb** [comment]
> 目前是确定 Copyleft 翻译成“左版”了对吧？如果定下来，我觉得可以和 GNU 上游把这个翻译统一起来。
嗯，但不知道现在 fsfs-zh 中该词翻译（以及翻译与否）有没有统一？
目前 GNU CTT 的《GNU 术语中文参考翻译(草案)》没有这个词的参考翻译。

**Comment by tonghuix** [comment]
据我所知，这里好多都是保持没翻译状态。慢慢统一用词吧。

**Comment by tonghuix** [comment]
我也看过这篇文章， 但是我又觉得在中文世界，这个 Copyleft 确实需要一个翻译。保持不译对传播不利。

**Comment by Hagb** [comment]
现有 gnu.org 的页面均使用原文“Copyleft”或“copyleft”。
而 fsfs-zh 中涉及到该词的大部分（15/20）的文章均使用“Copyleft”或“copyleft”，其余（5/20）以“左版”作为该词的译文。
是否要统一呢？有没有（以及“左版”算不算）“a good translation”呢？……

**Comment by tonghuix** [comment]
要不这次还是和 GNU CTT 一起讨论？左版的翻译来源可见 #227 。还有就是一旦确定了翻译，在《什么是 Copyleft》一文中咱们还需要用注释的方式，或者用括号的方式把这个写进去。

**Comment by Hagb** [comment]
如何“和 GNU CTT”一起讨论呢？是在 GNU CTT 的邮件列表里面讨论吗？

**Comment by tonghuix** [comment]
> 如何“和 GNU CTT”一起讨论呢？是在 GNU CTT 的邮件列表里面讨论吗？

我觉得可以和上次一样用邮件列表，不过我猜这次他们可能会坚定认为不翻译，或者提出用“著佐权”，我记得之前讨论的邮件里有人已经提出过这个了。

类似需要讨论的用词还有 SaaSS 的翻译。我认为 fsfs-zh 的翻译比较准确。

**Comment by Hagb** [comment]
@tonghuix emmm……看到邮件列表了吗？怎么办？

**Comment by persmule** [comment]
> @tonghuix 我认为 fsfs-zh 的翻译比较准确。
那就统一到“左版”。
毕竟 fsfs-zh 是我们搞的，没必要让别人干涉我们怎么翻译，他们喜不喜欢是他们自己的事。

**Comment by tonghuix** [comment]
为了同步起见，先按 GNU CTT 的用词要求改一下。我打算积极争取将 copyleft 有一个直接且容易说的汉语翻译，我个人很倾向于“左版”或“版左”

**Comment by tonghuix** [comment]
为了解决类似这样纠结的翻译用词问题，现在开了一个新分支 gnu-sync 并作为默认。如果需要保留旧有翻译则留在 master 分支，需要反馈到 GNU 官网的，则使用新的 gnu-sync 分支。
