### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#185]
5.2.1 最后一段中的“在你看了我们的推荐之后，如果你想要建议，你可以写邮件到licensing@gnu.org”中“licensing@”超出了范围

**Comment by tonghuix** [comment]
可能又要需要强行换行了。。。

**Comment by tonghuix** [comment]
也许可以啊，但是这也是我说的“强行换行”的一种

**Comment by Hagb** [comment]
@tonghuix 
CONTRIBUTIONS.md中说：
> 中英文混排时，英文和中文之间留有空格

这儿的空格应该是漏了吧？

**Comment by tonghuix** [comment]
看上去确实是漏空格了

**Comment by tonghuix** [comment]
这个有人修了么？

**Comment by Hagb** [comment]
@tonghuix 我在学校没有环境，修了也编译不了来看效果。你们修吧

**Comment by tonghuix** [comment]
这个修复了么？

**Comment by Hagb** [comment]
@tonghuix 之前加了空格之后就好了……换句话来说，修复了
