### ISSUE TITLE
关于注释的排版问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#186]
好像有不少注释被分开在不同的页面，甚至有的跨了3页……这算不算一个不足呢？

**Comment by tonghuix** [comment]
用的是 A5 纸张，这是 texlive 系统自动的吧，不过应该可以禁用吧

**Comment by tonghuix** [comment]
嗯我也看过这个问题，所以我认为可能是可以通过一些方法把这个特性禁用

**Comment by tonghuix** [comment]
如果能解决，就放在 2018.3 里

**Comment by Hagb** [comment]
@mytbk 这个问题该怎么解决呢？

**Comment by Hagb** [comment]
问题仍然存在：
在PDF的307页（书籍289页）的注释，垮了3页

**Comment by Hagb** [comment]
已经修复
