### ISSUE TITLE
有些注释不够规范？

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#187]
CONTRIBUTIONS.md里说
> 中英文混排时，英文和中文之间留有空格

但是有些注释里面是中文和英文（或者链接）之间是没有空格的。

**Comment by Hagb** [comment]
@tonghuix 好像还没完全补完，不用那么快close吧

**Comment by Hagb** [comment]
这周没时间搞了 下周周末吧

**Comment by tonghuix** [comment]
修完了记得 close 即可

**Comment by tonghuix** [comment]
这个修完就作为 2018.3 的一个特性吧

**Comment by Hagb** [comment]
@tonghuix 我们学校下周放中考假，我可以把它修完了

**Comment by Hagb** [comment]
应该绝大多数完成。

**Comment by tonghuix** [comment]
@Hagb 好，大家一起来检查吧！
