### ISSUE TITLE
迁移到新版 Pandoc

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/fsfs-zh#191]
开个 issue 追踪迁移新版 pandoc。

因为从 pandoc 2.0 开始增加了很多很多新特性，也许其中有咱们能用的上的，这样可以改善一下。https://github.com/jgm/pandoc/releases

@mytbk 有任何相关思路，请多多贡献出来！

**Comment by IFRFSX** [comment]
主要我担心我的mint系统上没有及时更新导致无法编译新书。
现在这本书似乎没错别字了，考虑一下打印传播的事情吧。

**Comment by tonghuix** [comment]
关于打印传播请在 #146 讨论。

**Comment by mytbk** [comment]
已经在 commit 2934d169fed9b78a72c04ee66e91e39a78cf922a 更新，同时使用有最新 fonts-noto 的 PPA.
