### ISSUE TITLE
英文句子的排版问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#192]
我注意到有些英文句子（这种句子在注释中为多）的单词间隔拉得很长很长，感觉影响了效果，我估计是为了单词分布在一整行里。像原书那样，把行末的单词拆开两行，中间用“-”连接会不会好一些呢？

**Comment by tonghuix** [comment]
我觉得这应该是 latex 排版的问题吧

**Comment by Hagb** [comment]
@tonghuix 你看怎么样好呢？

**Comment by tonghuix** [comment]
@mytbk 你知道有什么办法修改一下 latex 模板么？

**Comment by tonghuix** [comment]
我感觉这和 #201 是因为同一个问题。搜索了一下，英文里关于latex脚注就没这种问题，看来可能是中文的特殊性？

**Comment by Hagb** [comment]
> 我感觉这和 #201 是因为同一个问题。搜索了一下，英文里关于latex脚注就没这种问题，看来可能是中文的特殊性？

emmm……我试着把 #201 的那个注释中的中文和全角符号都改为半角的字符，问题依然存在。

**Comment by tonghuix** [comment]
> > 我感觉这和 #201 是因为同一个问题。搜索了一下，英文里关于latex脚注就没这种问题，看来可能是中文的特殊性？
> 
> emmm……我试着把 #201 的那个注释中的中文和全角符号都改为半角的字符，问题依然存在。

还有一种可能性，因为模板调用了 CTEX 包，可能是这宏包里强制让文本都是两侧对齐？

**Comment by Hagb** [comment]
已解决于#250
