### ISSUE TITLE
关于“neighbor”的翻译问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#193]
我查到 neighbor 还有以下两个意义（来自牛津高阶第八版“neighbour”的第3、4个义项）

- 身边的人；靠近的东西；附近的人（或物）
- 他人；世人

这个中译本中“neighbor”都译作“邻居”，以上两种应该更符合语境吧，会不会是更好的译法？
@tonghuix

**Comment by tonghuix** [comment]
参考英英解释更好
noun
1. a person who lives near another.
2. a person or thing that is near another.
3. one's fellow human being
4. a person who shows kindliness or helpfulness toward his or her fellow humans
5. (used as a term of address, especially as a friendly greeting to a stranger)

引自：http://www.dictionary.com/browse/neighbor

**Comment by Hagb** [comment]
@tonghuix 
牛津：[https://www.oxfordlearnersdictionaries.com/definition/english/neighbour_1#neighbour_1__17](https://www.oxfordlearnersdictionaries.com/definition/english/neighbour_1#neighbour_1__17)

> 1. a person who lives next to you or near you
> 2. a country that is next to or near another country
> 3. a person or thing that is standing or located next to another person or thing
> 4. (literary) any other human

**Comment by tonghuix** [comment]
所以就看读/唱着顺咯，当然肯定没有同行的意思。

**Comment by Hagb** [comment]
@tonghuix 没有。因为这个问题还没得出明确答案。

**Comment by tonghuix** [comment]
你就看着改呗。。。。

**Comment by Hagb** [comment]
@tonghuix 
拿不准啊。我在翻译方面还是极其业余的……
