### ISSUE TITLE
附录B表格的排版问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#197]
![screen](https://user-images.githubusercontent.com/10961094/41509797-e3fa8658-728b-11e8-922e-a4c29d8ab6e4.png)
如图："语言识标" 竖起来了，有点不和谐。能不能把 "语言识标" 那个标题改成空白的……

**Comment by tonghuix** [comment]
也许可以？

**Comment by Hagb** [comment]
![screen](https://user-images.githubusercontent.com/10961094/41515351-02a9ae76-72e1-11e8-93c0-c2b5bdc0a48d.png)
看起来不错

**Comment by tonghuix** [comment]
确实好看多了！
