### ISSUE TITLE
翻译问题2

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#203]
在“科学必须摆脱版权束缚”中，有一处的翻译(有疑问处粗体)：
译文：

> 某些大学——例如麻省理工学院（MIT）——已经采纳了某些政策以限制出版者的权力。**然而，更加强有力的政策是必需的，就像 MIT 允许个人作者“退出”（屈服）。**

原文：
> Some universities---MIT for instance ---have adopted policies to thwart the journal publishers' power.
> **Stronger policies are needed, however, as ones like MIT's permit individual authors to ''opt out'' (i.e., cave in).**

这里 ones like MIT's permit individual authors to ''opt out'' (i.e., cave in) 大概不在 Stronger policies 的范畴里吧（毕竟他还用了“cave in”一词）。我觉得这里的"ones like MIT's permit individual ..."前的"as"可能译成“尽管”会比较好

**Comment by tonghuix** [comment]
@nadebula 可否来帮忙解释一下？

**Comment by tonghuix** [comment]
我重新审视了一下，觉得原翻译就挺好。

**Comment by Hagb** [comment]
webmasters@gnu.org 的回复

> > In Science Must Push Copyright Aside:
> > Some universities---MIT for instance ---have adopted policies to
> > thwart the journal publishers' power.
> > Stronger policies are needed, however, as ones like MIT's permit
> > individual authors to ''opt out'' (i.e., cave in).
> >
> > What does "Stronger policies are needed, however, as ones like MIT's
> > permit individual authors to ''opt out'' (i.e., cave in)" mean? Is the
> > MIT's policies not enough strong?
> 
> Here is the policy the article is talking about:
> https://libraries.mit.edu/scholarly/mit-open-access/open-access-policy/
>  
> I think this is the sentence it is referring to:
> 
> | "The Provost or Provost’s designate will waive application
> | of the policy for a particular article upon written
> | notification by the author, who informs MIT of the reason."
> 
> It means that an author can avoid assigning copyright to MIT
> (i.e. opt out of the policy) if there is a good reason.
> This reason could well be a contract the author has signed,
> for instance to fund some research or write a book for a
> commercial publisher. In my understanding, "cave in" means
> that the author's willpower is not strong enough to refuse a
> contract that restricts access to knowledge.

**Comment by tonghuix** [comment]
那么目前来看哪种翻译更好呢？

**Comment by Hagb** [comment]
不知道……我纠结的是这里的”as“表示什么？

**Comment by tonghuix** [comment]
as 如果翻译成“正如”呢？

**Comment by Hagb** [comment]
我也不清楚…不知道 as 连接的两个部分是什么逻辑关系…

**Comment by tonghuix** [comment]
这个可以在 2019.1 版解决一下吗？

**Comment by Hagb** [comment]
要不发邮件问问这里的 as 是什么意思吧……我就是对这个 as 有疑虑。

**Comment by tonghuix** [comment]
可以啊，不过我认为这可以和 #204 放在一起问，争取一次性解决。

**Comment by Hagb** [comment]
您发还是我发？我现在在学校，不方便定时检查邮箱。

**Comment by tonghuix** [comment]
主要是你之前已经发过几次建立联系了，可能你来发更好吧

**Comment by Hagb** [comment]
好。我今晚发邮件，估计最迟明天早上醒来就能看到了。

**Comment by Hagb** [comment]
--------原始邮件--------
发件人： Therese Godefroy via RT <webmasters@gnu.org>
发送时间： 2019年3月23日 GMT+08:00 上午1:16:52
收件人： hagb_green@qq.com
主题： [gnu.org #1363819] Some questions

Le Ven 22 Mar 2019 10:04:11, hagb_green@qq.com a écrit :
> > In Science Must Push Copyright Aside:
> > Some universities---MIT for instance ---have adopted policies to
> > thwart the journal publishers' power.
> > Stronger policies are needed, however, as ones like MIT's permit
> > individual authors to ''opt out'' (i.e., cave in).
> 
> 
> As a conjunction, what is meant by "as" in the text? Does it mean
> "because"?
 
Yes. You could also replace it with "since".

> 
> >> In Giving the Software Field Protection from Patents:
> >>
> >> My suggestion is to change the effect of patents. We should
> >> legislate that developing, distributing, or running a program on
> >> generally used computing hardware does not constitute patent
> >> infringement. This approach has several advantages:
> >>
> >> It does not require classifying patents or patent applications as
> >> "software'' or "not software.''
> >>
> >> It provides developers and users with protection from both existing
> >> and potential future computational idea patents.
> >>
> >> Patent lawyers cannot defeat the intended effect by writing
> >> applications differently.
> >> What is "the intended effect"? Such as what GPLv3 does ?
> >
> > GPLv3 is a copyright license. It also tries to protect users from
> >  patent infringement lawsuits, but this is irrelevant here.
> >
> > I think the "intended effect" is the effect that the proposed
> > legislation is supposed to have. Since the conditions for obtaining
> > a patent don't change, lawyers don't need to twist the wording of
> > their patent applications any more than they do now. They get the
> > same number of patents, but patented programs will only be affected
> > when they are running in special equipment (e.g., a machine tool).
> > Patents will have no effect if the patented programs are running in
> > a general purpose computer (e.g., a laptop).
> 
> 
> Does "defeat the intended effect" mean trying to make the patents
> cover software running in the general purpose computer?
> (I still not fully understand.)

It means "defeat the proposed legislation".

The proposed legislation doesn't change the way patents are
granted, it only changes the way patents are _applied_.
It says that patents are only applicable if the software runs
on specialized equipment. Lawyers can change patent wording,
but this will have no effect if the software runs on a general
purpose computer.

**Comment by Hagb** [comment]
gnu 那边 Therese Godefroy 的回复：

> > > In Science Must Push Copyright Aside:
> > > Some universities---MIT for instance ---have adopted policies to
> > > thwart the journal publishers' power.
> > > Stronger policies are needed, however, as ones like MIT's permit
> > > individual authors to ''opt out'' (i.e., cave in).
> > 
> > 
> > As a conjunction, what is meant by "as" in the text? Does it mean
> > "because"?
>  
> Yes. You could also replace it with "since".

看起来是“因为”

**Comment by Hagb** [comment]
所以我认为应该是：

> 然而，更加强有力的政策是必需的，因为 MIT 允许个人作者“退出”（屈服）。

**Comment by tonghuix** [comment]
就这样，已经合并。
