### ISSUE TITLE
翻译问题3

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#204]
在”保护软件领域免受专利困扰“里面（有疑问处粗体）：
译文：

> 我的建议是改变专利的*效力*。我们应当立法规定，在通用计算硬件上开发、发布、运行程序并不构成专利侵犯。这样有几个好处：
> -   不再需要区分专利或者专利申请到底属于“软件专利”还是“非软件专利”；
> -   可以对开发者和用户提供保护，不论对于现存的还是将来潜在的计算思想专利；
> -   专利律师不能再通过以其他方式编写专利申请来消除**这种有意而为的效力**。

原文：

> My suggestion is to change the *effect* of patents.  We should
> legislate that developing, distributing, or running a program on
> generally used computing hardware does not constitute patent
> infringement.  This approach has several advantages:
> - It does not require classifying patents or patent applications as "software'' or "not software.''
> - It provides developers and users with protection from both existing and potential future computational idea patents.
> - Patent lawyers cannot defeat **the intended effect** by writing applications differently.

这里的 "the intended effect" 是指前文所说 “effect of patents” 吗？我认为：从语境上看不是，倒更可能是指像GPL那样的影响，如果是这样的话，那么译成“这种有意而为的效力”是不妥的（尤其是“这种”一词）

**Comment by tonghuix** [comment]
@nadebula 请帮忙解释一下吧。

我本人还是同意@Hagb 的理解，这里可能需要换一种说法，或者加一些译注。

**Comment by Hagb** [comment]
[webmasters@gnu.org](mailto:webmasters@gnu.org) 处 Thérèse 的回复：

> > In Giving the Software Field Protectionfrom Patents:
> >
> > My suggestion is to change the _effect_ of patents. We should
> > legislate that developing, distributing, or running a program on
> > generally used computing hardware does not constitute patent
> > infringement. This approach has several advantages:
> >
> > It does not require classifying patents or patent applications as
> > "software'' or "not software.''
> >
> > It provides developers and users with protection from both existing
> > and potential future computational idea patents.
> >
> > Patent lawyers cannot defeat the intended effect by writing
> > applications differently.
> > What is "the intended effect"? Such as what GPLv3 does ?
> 
> GPLv3 is a copyright license. It also tries to protect users from
> patent infringement lawsuits, but this is irrelevant here.
> 
> I think the "intended effect" is the effect that the proposed
> legislation is supposed to have. Since the conditions for obtaining
> a patent don't change, lawyers don't need to twist the wording of
> their patent applications any more than they do now. They get the
> same number of patents, but patented programs will only be affected
> when they are running in special equipment (e.g., a machine tool).
> Patents will have no effect if the patented programs are running in
> a general purpose computer (e.g., a laptop).

**Comment by Hagb** [comment]
按照 GNU 的回复，我原先的想法是错的，“这种有意而为的效力”是没问题的。现在倒觉得 defeat 译为“消除”似乎不太妥当，建议换个译法。

**Comment by tonghuix** [comment]
研究一下，defeat 翻译成啥比较好

**Comment by tonghuix** [comment]
defeat 翻译成 挫败 如何？

**Comment by Hagb** [comment]
发邮件问问吧……我不清楚这里为什么用 defeat……

**Comment by Hagb** [comment]
gnu 的 Therese Godefroy 的回复：

> > >> In Giving the Software Field Protection from Patents:
> > >>
> > >> My suggestion is to change the effect of patents. We should
> > >> legislate that developing, distributing, or running a program on
> > >> generally used computing hardware does not constitute patent
> > >> infringement. This approach has several advantages:
> > >>
> > >> It does not require classifying patents or patent applications as
> > >> "software'' or "not software.''
> > >>
> > >> It provides developers and users with protection from both existing
> > >> and potential future computational idea patents.
> > >>
> > >> Patent lawyers cannot defeat the intended effect by writing
> > >> applications differently.
> > >> What is "the intended effect"? Such as what GPLv3 does ?
> > >
> > > GPLv3 is a copyright license. It also tries to protect users from
> > > patent infringement lawsuits, but this is irrelevant here.
> > >
> > > I think the "intended effect" is the effect that the proposed
> > > legislation is supposed to have. Since the conditions for obtaining
> > > a patent don't change, lawyers don't need to twist the wording of
> > > their patent applications any more than they do now. They get the
> > > same number of patents, but patented programs will only be affected
> > > when they are running in special equipment (e.g., a machine tool).
> > > Patents will have no effect if the patented programs are running in
> > > a general purpose computer (e.g., a laptop).
> > 
> > 
> > Does "defeat the intended effect" mean trying to make the patents
> > cover software running in the general purpose computer?
> > (I still not fully understand.)
> 
> It means "defeat the proposed legislation".
> 
> The proposed legislation doesn't change the way patents are
> granted, it only changes the way patents are _applied_.
> It says that patents are only applicable if the software runs
> on specialized equipment. Lawyers can change patent wording,
> but this will have no effect if the software runs on a general
> purpose computer.

**Comment by Hagb** [comment]
emmm……回复似乎已经说得很明白了……
感觉这里直译“effect”一词很具有迷惑性，因为上文已经说了“effect”是要被“Limit”的，现在还“消除”、“抵御”……
要不意译一下？
“专利律师不能 通过以**不同的**方式编写专利申请来**抵抗这种法律**”
因为 intended 有 planned 的意思，而“这种法律”应该能明确是指上文的提议的立法。
原译文的“再”也很令人迷惑，我认为（根据 gnu 的解释）译文这里是不应该加的。

**Comment by tonghuix** [comment]
就这样，已经合并。
