### ISSUE TITLE
关于：传播本书，自由软件相关的问题讨论

### ISSUE THREAD

**Issue by IFRFSX** [beijinglug/fsfs-zh#208]
为了让互联网时代的人们能得到应有的自由，让社会更加美好，书里面就说到了，让作品的可再分发合法化，让功能性作品（比如软件）自由等等。

最近我调查了一些群，很多人还是错误地将非商业复制分发书籍什么的称为“盗版”，并且将其当作一种恶行。并且他们认为只有专有的东西才能让作者获得收入（还有些其他的混淆，比如把“保护智力成果权”和“禁止再分发”联系到一起，认为所谓的“盗版”是“不尊重智力成果”）。也有的用实物类比，但是他们忽略了——实物不可复制，但信息是可以几乎无成本地复制的。我曾经试图和他们讲理，他们就直接乱扣帽子，比如“幼稚”“小孩子”“过于理想化”“多读点书吧”之类的。但是现在的大多数书籍，已经把版权法和专利法扭曲了，初衷都被扭曲了。我为什么要看呢？

书里面也提到过，现在的版权其实保护的大多还不是作者，而是出版商。我见过某公司的文章，上面把版权法的历史刻画为保护作者利益的东西，而不是促进创作的东西。还有个相反的，揭露的文章：http://www.sohu.com/a/231790376_104421

现在我们来讨论下，如何更好地传播这本书。我看到有个已经关闭的issue提到，因为有关于社会的思考还有一些其他原因，纸质版还不能出版，那么除了大量转载和上传外，还有没有其他的传播途径，可以让更多没接触过自由软件思想的人来读文章？

**Comment by IFRFSX** [comment]
@Hagb @tonghuix 我们最主要的阻力在于那些财团和发行商，错误的东西是他们宣传的，而且他们也有足够的势力去暂时掩埋真理。所以我们要做的就是——揭露。

**Comment by tonghuix** [comment]
前年吧？和LinuxCN网站有合作，他们在微信公众号上会不定期发一些这里的文章。

之前去国内国外开源会议做演讲的时候也会顺带广告，有些人会关注但是效果不太好。还可以找国内有影响力的社区合作，但是这些社区对自由软件的态度偏负面，要先把他们的领导者洗脑才行。

**Comment by IFRFSX** [comment]
@tonghuix 大佬，这怎么能叫洗脑，我们传播的思想是在揭露不好的东西，传播好思想，为了把他们从财团的洗脑里面拯救出来呢！=v= 这叫——传播真理

**Comment by IFRFSX** [comment]
其实我也有自己的社区，在我接触自由软件之前，它是一个玩我的世界的小团队，后来因为网易代理导致联机平台之类的用不了了，后来我只得宣布解体。但随后不久，又改了名字重组了，群号是128242181，因为没有合适的自由替代品，我就继续在用QQ。新的社区名字叫“冰枫蓝叶自由文化社区团队”。，Hagb不久前也加入了。
前面发的链接：http://www.sohu.com/a/231790376_104421 是我找到的，揭露那些财团扭曲版权法初衷的文章，发这个文章的公众号，贵方是否可以考虑合作下？

**Comment by IFRFSX** [comment]
现在我发现，自由软件的分支——开源软件的支持者里面，有些人纯粹就是分享精神，这也导致了很多人误以为“开源就是做公益”（以前我也以为是这样，直到我看了这本书），顺带让自由软件也被误解了。我们应该要注意强调，这不是公益活动，而是反专制的，夺回计算控制权的，阻止版权和专利过度扩张的活动。
一说起这个事情，我想起来一家很有特色的具有自由软件思想的公司——Purism（https://puri.sm/）。他们的计算机设备除了一点blob外，其他的软件部分都是自由软件组成的。我翻译了他们的一篇文章：https://my.oschina.net/u/3312265/blog/1840253。他们的PureOS发行版的地址：https://pureos.net/，源码和二进制包的地址：https://repo.pureos.net/pureos/pool/

**Comment by tonghuix** [comment]
@IFRFSX 你思维好奔逸啊。。。。。请回到主题吧

这些公众号主要是看上去很好，但是实际合作未必能谈妥。还有另一个问题是公众号的运营需要一定阅读量的，内容运营机构对这个非常看重，你觉得大众会有多少人在意自由软件里的自由呢？

我认为关键还是民智未开啊。

**Comment by IFRFSX** [comment]
@tonghuix 我觉得也是因为民智未开。现在我来说一下，我想到的传播方法，和我接触到的那些人的情况（对GNU/Linux的态度和自由文化的态度）

1. 一开始我想到的方法是遵循GFDL 1.3 许可证的要求把书籍打印出来，然后卖给某些书摊和报刊亭。但是后来大佬您告诉我这会违反大陆的法律（与许可证无关）。后来我又想到几个方法：

+ 先打印一本，然后借给别人看，然后再借给下一个人。。以此类推！
+ 将书籍的内容发布到一些博客的网站（微博，网易LOFTER，OSC，以及其他等等），然后在标题上添加一些容易被搜到的关键词。
+ 将FSFS的在线刊登网址到处发，引起网虫们的注意。
+ 打印其中几页，在上面挂张纸，写上各种信息，包括GFDL要求的那些，还有FSFS在线刊登的网址，然后扔在某些地方，人们会去捡着看。

2. 我曾在班里演讲过关于GNU/Linux的历史，但是大家不感兴趣哦。我们班里，有三个人计算机玩得6，分别是我们班长，专业课的课代表和我——他们只是在虚拟机上使用GNU/Linux，物理机用的是Win10，而我是在电脑上装了两个GNU/Linux发行版（Mint和Trisquel）和Win7（用于剪辑视频和编歌等），大部分时间还是用Mint。不知道为什么，Win10似乎是很多人心目中的标准操作系统呢！现在我

为了让更多人理解深层次的问题，我在某些群里试图和某些人争论Kindle好坏，和关于书籍的再分发问题，有些人不解，一个劲儿地强调“正，说得好像还有更早的一次（那时候我还没接触自由软件的世界），因为老师要求学英文歌曲，我将酷狗音乐里面的音乐缓存提取出来，而没有付费，结果有同学就跟我扯版权呀什么的。。感觉他们还是只知道遵守规则而不懂得打破规则呢。

噢对了，我见过一个很棒的网站，是https://getgnulinux.org，可以帮助新人们接触自由软件思想。我觉得你们可以和他们一起合作。

**Comment by tonghuix** [comment]
我很赞赏你在班里宣传自由软件的做法，诚然有些人可能没啥兴趣，但是真正有兴趣的人迫于班里的社交压力并没有真正发声，但是他/她可能会在私下自己去搜索或者找你聊。民智虽然未开，但是播种土壤的工作我们需要像你这样一步步去做的人。当然宣传策略可以稍作改动，想想自由软件对学生群体的真正好处（少说省钱相关），另外男生女生的诉求可能也是不同的，不妨花点时间思考思考。

关于 GetGNULinux 这个网站超级好，但是我觉得他们的主题还是引导大家安装使用 GNU/Linux，和泛泛的自由软件宣传不同，盲目合作也不太好。

至于宣传本书的方式，试过的一个可行的办法是用现在人已经接受和使用的方式来潜移默化的改变，比如他们不是在讨论 kindle 的好坏吗，那你就把这书的 kindle 版在群里传，让他们自己慢慢看慢慢理解。当时和 LinuxCN 公众号的合作也是看中大众现在用微信公众号的多，这种宣传能起到一定作用。顺便说，那个公众号发布以后的下面评论我也看了，能很明显感觉到软件开发从业者对自由软件的误解之深，很多误解是他们认知问题，还有一些误解是我们宣传不到位的问题，但是慢慢的误解性的评论减少了。

发到博客网站的做法并不靠谱，这是因为现代人用博客的很少了。另外FSFS的在线阅读现在是用的免费的 readthedocs，但是这货貌似在国内被墙，慢的要死。也需要志愿者在国内架设相应的服务器来镜像。

另外可以打印一两本在你班里传看，暂时先不要想影响很多人，只要先影响身边的人就够了。

**Comment by IFRFSX** [comment]
GetGNULinux是在鼓励人们使用GNU/Linux，但是也在向人们传播自由软件的思想。我倒是觉得，我们应该先去帮助几个自由软件公司（例如Purism），让大家知道自由软件的商业模式是很好的。

我在百度贴吧见过一个人，她坚持说“不是所有的软件都可以用开源+服务的方式盈利”，我跟他说RMS卖过定制（受雇佣帮助客户升级改造软件），她来了个“那件事太理想化，在这个世界行不通”。对这种话我真是无语了，不就是简单的雇佣关系么，这也会“在这个时代行不通”？？只能说明她在搞偏见。

自由软件最大的阻力在于其敌人——专有软件占领了市场，并且已经让市场的规律发展得有利于专有软件发展而不利于自由软件。再加上很多人总是把软件什么的跟实物类比。

没错，实物和信息/数字类作品的制作者都有权得到报酬，但是得到报酬就必须得要将信息/数字作品设置一堆限制来做到吗？这种情况下只有权力持有者可以复制和修改信息，没有随着互联网的发展而对政治和商业制度做足够合适的更新，感觉是在互联网时代模拟印刷时代，不但让社会运行效率降低了不少，而且还浪费了大量民间的力量。打个不是很精准的比方——这就好比，某人明明拥有了一个科学计算器，可是他习惯于算珠的操作方法，所以就直接让科学计算器模拟算珠，这样他可以适应了——然而却将科学计算器的高效率和自由输入数字等特性完全掩盖了。

**Comment by IFRFSX** [comment]
自由软件的好处，我觉得对于学生而言，最大的好处就是有利于学编程，个性化定制方便。。当然如果说雇人来给自己定制这一般不是学生能承担的。

**Comment by tonghuix** [comment]
我觉得学生群体的利益悠关的地方可能更多的是隐私和廉价的使用。

**Comment by IFRFSX** [comment]
学生，自然最在意的是学知识。照着注释琢磨代码，或者学习怎么去使用和配置一款软件，再怎么样也比那落后而又污浊的应试教育好很多了。虽然我目前还根本看不懂复杂的代码（我只会较为简单的Python3）。QwQ

**Comment by tonghuix** [comment]
问题是这个思想也不新颖和超前，1985年就提出来了啊，至少十年以后你们才出生啊。主要是对他们来说需要革新的比较多，不过学生群体毕竟年轻，接受新事物的能力会比较强，你的这个做法很值得称赞。

**Comment by IFRFSX** [comment]
大佬，你可以看看我的fork版本里面的两张新的图，是魔改版的封面。/doc/cover_IF.png/.xcf，pictures分支。

**Comment by IFRFSX** [comment]
对于新颖与超前，这应该和出现时间没多大关系，新事物适应未来发展，这是最重要的。

**Comment by tonghuix** [comment]
@IFRFSX 关于这个封面魔改，首先肯定是不会合并的，因为尊重原书。现在这封面就是从原书仅少量修改过来的结果。不过你私下传播的话，那就管不了了，不过至少将作者和译者的劳动在明显位置提及，另外坚持 FDPL 许可。

接着说传播的问题。目前来看，我认为自由软件的出现恰好符合了现在的社会现实，特别是斯诺登曝光棱镜计划以后，在国内大家也对大规模监控和间谍软件有了更多堤防。这倒是宣传自由软件的好时机。

**Comment by IFRFSX** [comment]
我知道你们很有可能不会合并的，所以单独开了个pictures分支，这样就不影响我提交的PR了。
我发现现在很多人对斯诺登有误解，比如他们污蔑斯诺登“作死”， 引发民众对政治的“不信任”， 破坏了“反恐战争”， 破坏了美国的“世界第一”等等。这是他们被专制主义思想过影响的结果！国家是为人民而设立的，人民不是为国家而活的。这是国家存在的意义。所以如果ZF连民众的隐私都要窥探，这种权力机构还有存在的必要吗？至于所谓的反恐战争，美国自己就比较kb主义——看看那伊拉克，在萨达姆的统治下虽然不够民主，但是人民好歹物质生活不差，也比较安全，萨达姆被美国推翻以后，反而恐怖疯子到处肆虐，原来所谓世界第一的美国就这样进行“反恐战争”，徒增笑耳。而对于所谓的世界第一，我认为国家再怎么强大也比不上人民的权益重要，人民的权益（比如隐私权，比如分享好东西的权利）无法保证，国家再强大又有何用？

所以说，现在很多人连斯诺登的做法不理解，推广抑制间谍行为的自由软件就有些难了。既然那些专有软件和不可分发素材的支持者总是以实物类比，说“你拿（用）别人的东西要对方同意（授权）”，那我们也可以说，“你将物品发放出去了还搞那么多限制，这合理吗？”。

您可以在EMail上和我私聊，我的邮箱有两个：
1079092922@qq.com
IFRFSX@protonmail.com

**Comment by IFRFSX** [comment]
后来我仔细看了看您的那篇文章，很透彻地分析了自由与开源相关的东西，非常好。如果大部分人都有您这样细致的思维，那么社会将会远比现在发达得多。只是有几个地方，我有不同的看法：

>所以只要不违反开源许可证，任何对促进商业发展，简言之就是能赚钱的商业模式都可以使用

为了坚持自由软件的原则，在市场上我们不能使用非自由软件或者SaaSS等违反自由软件原则的方法来作为商业模式。

>我希望以后不会再有”自由软件“和”开源软件“的区别，最终能够融合在一起

通过对接触过的人的调查，我认为这个是很难做到的，并且还会造成不必要的矛盾。
因为坚持开源思想而不是自由思想的人好像大多都不具备自由精神，我曾经在交流ReactOS的某个群里见过两个人，他们先是怼GNU GPL和FSF，说，“这个世界远比FSF想象的美好”，然后说，不用GPL，也会“有很多人愿意开源的”，接着另一个人捏了一个奇怪的词汇，叫做“专有自由软件”——在他看来，GPL不允许代码往别的LICENSE软件里面用，这是另一种专有。我试图和他们达成共识，结果最终因为理念不能达成共识而闹得不欢而散。（比如前一个人还不反对锁死设备的行为，为这个还争了老半天。。）

有趣的是，我认识的一个开源支持者还在osc评论过一句“真正的开源爱好者是不会反对闭源软件的”。而自由软件的思想是消灭专有软件。对专有软件的态度也是一个因素。
在这方面，我跟RMS和FSF的其他核心成员的想法是一样的——自由软件是自由软件，开源软件是开源软件，哲学思想是完全不一样的，二者不是敌人，但是（从理念上）也无法达成共识。大佬您提到的“很多人会标榜自己爱好的是“自由软件”，而不是“开源软件””，这是我，我将他们统称为“开源社区”或者“开源方”。不过我并不会去“以鄙夷反对的表情和态度对待”。

**Comment by tonghuix** [comment]
@IFRFSX 这段评论真应该放在文章下面的评论栏里。。。

**Comment by IFRFSX** [comment]
我一想起那两个人我都觉得哭笑不得……不过，现在我们来聊聊其他的话题吧。

大佬，最近我在UEFI.org看了一下，发现说UEFI组织虽然不收取授权费，但是却要求使用UEFI规范就必须得填好一张协议，提交自己的信息，然后才能使用和复制分发。那么，grub2这样的自由软件是怎么支持UEFI的呢？UEFI的文档貌似不允许随便用。是否是因为没有专利限制而只有版权限制，所以可以按照原来的标准写出不同的实施方法呢？

他们那个页面要求，以下UEFI标准仅供阅读。下面也有ACPI的标准，ACPI是不是也得授权？那受到影响的GNU软件包就更多了。。

**Comment by tonghuix** [comment]
关于 UEFI 要请 @persmule 大佬来回答了。

封面的话，就不管你了，只要合规做啥都行。

**Comment by persmule** [comment]
可以认为 UEFI 是一套 API，实现这套 API 和调用它是两码事；grub 需要的是调用。ACPI 也是一样。

**Comment by IFRFSX** [comment]
@persmule 谢谢您的回答。

主要是因为Grub2的引导文件里面有efi文件，这个似乎也是使用了UEFI的格式，所以我才会担心。

现在我们自由软件世界有Coreboot和SeaBIOS，但使用它的计算机制造商却不怎么用它，都在用UEFI。目前我所知道的，只有Purism公司是坚持自由软件思想的高端计算机制造商，其他的比如minifree好像都是改装或者没那么高端。我见过一个叫[TianoCore](https://www.tianocore.org/)的固件也是实现了UEFI API的，据说它是通过intel发布的一些代码实现的。

照理说能获得实现ACPI的权限也应该可以获得UEFI的权限，但Purism好像只是用了ACPI，是不是因为ACPI不属于UEFI规范的一部分，所以不用授权？

最后，Coreboot除了Purism和谷歌ChromeBook外，有没有其他公司使用？听说AMD支持的。

**Comment by persmule** [comment]
ACPI 不是 UEFI 的一部分，只是 UEFI 继续沿用 ACPI 而已。

**Comment by persmule** [comment]
TianoCore 是 UEFI 的参考实现。

**Comment by IFRFSX** [comment]
@persmule 所以说，因为没有专利，参考原版文档制作出像tianocore这种不一样的UEFI实现对吗？

**Comment by persmule** [comment]
不对——你懂不懂什么叫参考实现？！
说白了，TianoCore 才是原版 UEFI。

**Comment by IFRFSX** [comment]
@persmule 不好意思哈，前面我理解错了。意思我大概明白了——UEFI是参考TianoCore的。因为需要单独许可，所以UEFI一般不可以用到自由软件项目里面，但是调用是不受限制的。但是TianoCore因为是两句话版本的BSD许可（BSD BSD 2-Clause），所以可以用，这样理解就应该没问题了吧？

**Comment by persmule** [comment]
你不知道业界惯例：uefi.org 不许可，你就不能声称自己的硬件产品实现了 UEFI；但这一般限制不了自由软件项目，因为自由软件项目可以声称自己实现的是“一个很像 UEFI 的”东西，就像 mesa 的做法。

**Comment by IFRFSX** [comment]
我记得前不久还有人跟我说tianocore是coreboot的EFI模块来着。。

**Comment by persmule** [comment]
tianocore **可以用作** coreboot 的 EFI 模块。自由软件么，只要违反计算机系统的规律，你想怎么用都行。

**Comment by IFRFSX** [comment]
现在我明白了为什么要求不能在未授权的情况下声称实现了UEFI是在限制厂商，虽然他们不收取授权费，也可以用您所举的那个例子，用“很像”“类似”的理由来随便实现。
我来举个简单的例子，看看能不能描述得形象点儿：
某个使用了UEFI的厂商，没有授权，所以他不能说他实现了UEFI，有一天某个买电脑的人来了。
+ 买家：你们厂子的主板有支持UEFI启动么？
+ 厂商：这个……没有！
+ 买家：算了，我去买别的牌子吧
+ 厂商：QAQ

**Comment by IFRFSX** [comment]
@tonghuix 最近想到一个传播方案，等我的那两个PR彻底完成合并以后，可以让FSF他们把本书的下载地址放到GNU中文页面上让来访者下载，还有就是贵方在北京搞线下活动的时候跟客人们推销一下印刷版本，是不是很好呢？

**Comment by tonghuix** [comment]
首先说，FSF要想官网挂出来关键是要将翻译同步回 GNU 官网，也就是 #166 说的是前提。要不然他们也不给挂，之前和 FSF 谈过这个问题，没办法只能先贡献回 GNU 才行。

2016 的时候已经推过一次，线下活动新人来的不多。不过我已经退出 maintainer 快一年了线下活动参加也少了，可能还需要请 @persmule 来给你讲讲现在的情况，线下推广此书的也要问问他的想法。

**Comment by IFRFSX** [comment]
@tonghuix 我发现构建这本书的时候，问题也会时不时出现——刚刚我用我github上的修改版去build，结果pdf生成一直失败，epub倒是成功了，然后我用calibre转换成PDF，换了个字体，可是页码没像你们build的那样标在目录里面。以前试过epub——>docx——>odt——>修改，尽量不动行数，然后一篇一篇手动写上页码，但是那样的话转换为文档也会打乱排版，所以也就只能转换一个不带页码的了……QAQ打印出来用碳素笔写上页码。

话说，EPUB也可以直接打印的对吧？

**Comment by tonghuix** [comment]
因为这是另一个问题了，需要另开新 issuse 。顺便提醒如果汇报类似这种 build 失败的情况，需要包含如下信息，这样会帮助分析并解决问题：

* 软件版本（比如：你 fork 以后的某一个提交 bc0a81d2e18160302e623de270e222f5b37e03ef）
* 编译环境，包括操作系统、发行版、指令集架构（amd64/armelf/ia32/...etc），桌面环境、渲染器等可能也需要说，如果你汇报的是和桌面系统有关的
* 编译器或构建所用的软件及其版本（比如这里就是 Pandoc，其他的可能是 gcc 啊或者 clang 啊。。）
* Build 的时候用的库及其版本，有些使用 cmake 的软件会在 build 一开始放出一个列表里面会写
* 编译时用户输入的命令行，包括完整参数，如果使用 build 脚本需要把脚本内容告知（比如这里你是用的自带的 makefile 构建的吗？输入了什么命令呢？）
* 出错时的输出结果，可能需要用命令行重定向的方式来导出成一个文件。或者有的软件会自动保存编译 Log，把这个 log 尽可能完整发出来（可以隐去敏感信息）
* （可选）SELinux 状态或防火墙状态
* （可选）网络流量抓包或 tcpdump，如果涉及网络程序这个是必须的
* （可选）硬件型号、线路连接图、PCB 图或 Gerber 文件，如果是开源硬件项目这个也是必须

**Comment by IceCatX** [comment]
@tonghuix 我又帮你们抓到个不易被察觉的bug——

从实践角度讲，出版量最大化这一最终目标使得出版商可以如此论述：“某种行为正在削减我们的销量——或者我们认为它将会这样——因此，我们假定它使得出版量下降了一定的未知数量，因此它应当被禁止。”我们将会得到这样一种不可容忍的结论：公众的利益应当以出版商的销量来衡量，大凡对大众媒体公司有利的东西，对美国也都是好的。

“大凡对大众媒体公司有利的东西”的“大凡”是错字，应该改为“但凡”。

请修正。

因为写错的只有一个字而已，所以我就不发PR咯。

**Comment by tonghuix** [comment]
要么你自己修，要么等别人来修。

**Comment by IceCatX** [comment]
@tonghuix 

我为何会对这个那么热心？怎么就成了因为我只想出名？我本人的名气，我放在次要。

我就说实话吧——因为我想赶快让更多人来看这本书，解除他们的被洗脑！！！！！！！！！！！！

现在自由世界情况是极其危急的，如果再让M s 用WSL之类的花哨东西把自由操作系统的用户全带跑了，然后灌输专有的思想，后果是什么，不用我说吧？

两年前我在混MC圈子的时候就极其厌恶那些专有软件的专制思想，例如有一些玩家把长得像MC的方块沙盒都偏见地说成“盗版”“仿制”（除了迷你是真的抄袭外），虽然我玩得厉害，但我宁可不上传到多玩盒子而导致无法大量增加我的名气，也不会接受多玩要求在地图里面说明“已授权多玩盒子，禁止转载”这样的条件！专制主义甚至1984思想的散布已经达到如此地步，我干嘛还要继续？这也是我不怎么再参与MC圈子，改玩Minetest的一个原因。在 Minetest Forum 我还魔改过一个纹理包和做过几个皮肤，有人还给我的魔改版纹理包提交过issue帮我修正小问题。

现在明白为何我对这个话题特别感兴趣了吧？

**Comment by IceCatX** [comment]
@tonghuix 噢对了，你可以看到，我在那个GPL PR里面，我突然关了然后打开，那是不想让某些人看到罢了。

**Comment by tonghuix** [comment]
@IceCatX 呵呵你还耍大牌哈，自己看看贡献者的贡献量排名 https://github.com/beijinglug/fsfs-zh/graphs/contributors 你觉得你有这个耍大牌的资本吗？

**Comment by IceCatX** [comment]
@tonghuix 
你所谓的耍大牌是什么意思？别总说暗语可不可以？
还有就是，对于你在那个pr下回复的东西，请你尊重OSCHINA的人们，如果我所料不错，人家小编推荐我几篇成果，应该是因为我认真去做了，认可我的工作态度和劳动成果，然后鼓励我继续改进，继续多发新东西。我说我的东西被推荐，不是我有多骄傲，而是出于对作品被认可的高兴罢了，别随便对人妄加评价行吗？

后来那篇gpl翻译我又改进了多次，跟之前的漏洞百出可不一样。

我跟oschina的官方人员接触过，而且oschina给我的印象也非常好（FSFS就是我在oschina上搜到的）。所以，请不要再诋毁oschina。

最后，请把gpl的那个pr上，那2个人主动损我的，我反击的，你给他们帮腔，侮辱osc的话，都删除掉（最好彻底删除那个PR），我就忘了这件事，我们还是合作伙伴。

**Comment by IceCatX** [comment]
@tonghuix 
最后，我提醒您，我可不是像你表面上看上去那样喜欢炫耀，自以为是，或者骄傲，不听劝等等，我也从不轻易发火（触碰逆鳞除外）。我再说一遍，前面那个小错误是我检查不仔细造成的，现已修复。请去我的oschina博客获取更新。

**Comment by IceCatX** [comment]
@tonghuix 

你说的耍大牌应该指的是我将我们社区的名字贴在修改版上吧，这个还需要资本？GFDL里面没有要求过必须有所谓的“资本”才可以造修改版吧？

最后，就算我不愿意听那两位前辈的意见，那不能被认定为我“不听意见” “拒绝批评”。难道我不听他们两个人的意见就代表我不听任何人的意见？这个逻辑好像不对哦。

至于贡献量，别忘了我来的时候这本书就翻译得差不多了，这时候我就算想多做贡献也找不到入口。

**Comment by IceCatX** [comment]
https://beijinglug.club/announcement-2018-ddau/

贵方不久前提到过deepin发行版，正巧我平时喜欢玩虚拟机，稍微玩过deepin，便说上一说。

我测试过Deepin，首先它默认没有"add-apt-repository"命令这一点非常麻烦（尽管你可以自己手动安装），并且其自带软件源是固定的。这是如此自信大多数用户都不用第三方源么？

>sudo apt-get install software-properties-common

如果需要，请输入以上命令添加add-apt-repository命令。如果需要删除某源，请用管理员方式打开 /etc/apt/sources.list

虽然我接触GNU/Linux才一年多，但对Windows有6-7年的经验！并且对其上面的软件和装机、配置很熟练和了解，所以

对于贵方所说的“深度（deepin）到底是一个什么样的 GNU/Linux 发行版”我可以做个回答：

+ 它稍带有点模仿Windows的倾向
+ 商店内带有大量Windows上的国产软件，还预装非自由的Steam，似乎是在通过Windows软件来快速形成生态圈（自带 crossover）。
+ 界面很漂亮，易用性强，这方面甚至可以说它能够与Win10比肩了。
+ Deepin自己开发的软件基本都是自由（开源）的。
+ 字体是非自由的，详情请参阅：[字体公共授权书](https://www.deepin.org/font-license/)

总的来说，Deepin 从易用性和功能上可以说除了前面说的那个问题，基本完美，GUI也很漂亮。但是自带大量非自由应用注定它无法用来帮助用户获得他们应有的自由，甚至会引导用户们去多接触非自由应用，有利有弊，如果你是自由软件的坚定支持者，请不要将 Deepin 作为主力系统。

**Comment by IceCatX** [comment]
@mytbk @tonghuix @Hagb 

最近找到一本书，很有趣，要不要一起来看看呢？[点击进入](
https://en.wikibooks.org/wiki/FLOSS_Concept_Booklet "FLOSS_Concept_Booklet")许可证：CC BY-SA 3.0

**Comment by tonghuix** [comment]
不错。值得一看

**Comment by IceCatX** [comment]
RMS前辈在FSFS里面有反对知识产权这一概念的文章，这里也有一篇，分析也是很深入的：
[文章链接](http://www.sohu.com/a/161834924_611098, "丹·桑切斯┃​知识“产权”是盗窃 ")

**Comment by IFRFSX** [comment]
@persmule @tonghuix 我前面那几句只是表达我自己的看法。尽管我不太喜欢git的某些特性，但不喜欢归不喜欢，我不会乱操作。每次发PR的时候我都是在尽量按照 @tonghuix 说的方法来发PR。

那次混合PR的事情是我一开始并不知道翻译那个词为私有是贵方特意为之，很抱歉，下次我会提前在issue里面说详细点，你们答应了我再发PR。

还有就是对于GPL的那个问题，因为当时翻译工具在两个词连起来的时候，把  有效地  的  “地” 换成了  “的”，我因为一时大意就搞错了。后来我抽出时间仔细看了一下，在自己的oschina博客里面把那个错误修正了——“有效地专有化”。如果你们还想要那个翻译，可以直接复制全文。如果还有问题，我还会继续修正。

目前我是暂时没发现错字，如果有，下次给你们发PR的时候我还是会按 Mr.Tong 说的来发不带混合的PR，按照你们的习惯。

若是还有遗漏之处，还请几位前辈不吝赐教。
