### ISSUE TITLE
proprietary software译成“私有软件”还是“专有软件”

### ISSUE THREAD

**Issue by nadebula** [beijinglug/fsfs-zh#210]
RMS 在 Why call it the Swindle 一文中提到，名字代表了立场，因此要对各种龌龊的东西（nasty thing）进行最深刻的批判，否则将起到使其合法化的效果。对于私有软件（proprietary software），“私有”一词就对其经济本质（私有制，或者具体地说，对代码的私人占有）作出了最深刻的批判。任何其他翻译方法都或多或少地未能深刻揭露其本质。

有人质疑软件自由运动对私有制的批判，但事实是 RMS 本人是明确反对私有制的，在此仅举几例。其一，RMS 本人的文章“为何软件不应该拥有拥有者”（Why Software Should Not Have Owners，<https://www.gnu.org/philosophy/why-free.html>）这是很重要的一篇文章（尽管没有出现在第三版的书中），直接否定了对软件（代码）的私人占有。其二，FSF 的 30 周年视频“用户自由”（User Liberation，<https://www.fsf.org/blogs/community/user-liberation-watch-and-share-our-new-video>），在提到左版许可证的时候，强调了其目的使得软件“无人可以拥有，谁都可以使用”（nobody could own; everybody could use，位于大约 1:32 位置），这也是对私有制的否定。其三，RMS 的个人博客上的一则评论，发表于 2018 年七月 5 日，标题为“英国的全职作家”（Full-time writers in the UK，<https://www.stallman.org/archives/2018-jul-oct.html>），评论中提到 RMS 本人反对公司将股东利益放在首位，这是对资本主义生产关系的批判，自然也批判了资本主义制度的根本问题（生产资料私人占有，即私有制）。

有人提议 GNU 官方的中文翻译是“专有软件”，但即使如此，也并不意味着我们必须不加批判地继承。相反，这是能够体现出我们的贡献之处，通过更加深刻地揭露私有软件的经济本质来纠正和改进所谓官方翻译中存在的错误和不足之处。不必过于在意是否会被所谓的官方认可，如同 RMS 所说，如果能够拒绝所谓流行度的诱惑，将会更加强大，参见“X Window System 陷阱”等文章。

还有人提议“私有”（proprietary）容易和“私人”（private）相混淆，因此应该避免使用。这是似曾相识的开源派逻辑：因为“自由”容易和“免费”混淆，所以我们要说“开源”。即使真的会引起混淆，这在 RMS 的文章“自由和非自由软件的分类”（Categories of Free and Nonfree Software）一文中已经有了详细的解释。而为了“避免混淆”而未能进行最深刻的批判则是更大的瑕疵，两害相权取其轻。（说到这里回应某人对于“私有”和“私人”问题的争论。如果我自己写了一个软件但是压着不发，它属于用户群体只有我的“私人软件”（private software）。虽然没有行善，但也没有作恶。然而，如果我哪怕只对一位用户以私有许可证发布了一段 Hello World，就是实实在在地作恶了。）

最后，借用某人曾经对我说过地话，希望某些人“多做有益于社区的事”。同时我之前说过的话仍然有效，如果执意将“私有软件”改为其他，我承诺一定会采取必要措施（有可能是极端措施）来捍卫自己的立场。

**Comment by tonghuix** [comment]
你应该直接回复一个多月前的那个 issue #200 。况且那个 issue 并没有 close，也就是说，依然在讨论当中，并没有得出结论。而 PR #176 也没有合并，还需要一些小改动，更何况即便合并了也可以再改。

私有还是专有确实是个问题，如果在 GNU 官网搜关键词“专有”，有 [9 个结果](https://www.gnu.org/cgi-bin/estseek.cgi?phrase=%E4%B8%93%E6%9C%89)，搜关键词“私有”，也有[ 9 个结果（只算简体中文）](https://www.gnu.org/cgi-bin/estseek.cgi?phrase=私有)，如果算上繁体中文和日文的话，那么就是 17 个结果。而这些包含“私有”的繁体翻译有几篇是从简体直接转换而来。和台湾朋友交流的时候发生的怪现象是他们也是混淆着说私有和专有，证据就是如果搜索繁体“專有”，则有 [12 个结果](https://www.gnu.org/cgi-bin/estseek.cgi?phrase=專有)。

@nadebula 例子中的 Why Software Should Not Have Owners 一文的繁体翻译，台湾那边也是将里面这些翻译为了“专有” https://www.gnu.org/philosophy/why-free.zh-tw.html。很希望此文的翻译者 Cheng-Chia Tseng @zerng07 能帮忙解释一下当初为何译为“专有”？

**Comment by IFRFSX** [comment]
@nadebula @tonghuix 
RMS大神反对的是禁止复制修改，但并不反对你将软件自己留着用而不发布——而这正是一种私人或者私有财产。**如果反对私有制，那干嘛不直接说软件不共享是不道德的，而不是禁止复制修改不道德呢？**RMS大神的观点很明显反对的是专制，而不是私有。本书的[《自由与非自由软件的分类》](https://fsfs-zh.readthedocs.io/zh/latest/categories/#private-software)里面写到过，

>自由软件关乎的是自由，而非可获得性。总的来说，我们不认为开发一款软件但不发布它是一件坏事。

所以说，反对的并不是私有制。
我反对使用“私有软件”这个翻译的最根本原因并不是因为与私人软件搞混——这是次要原因。最最根本的原因是不贴切。非自由软件最大的特点并非它被某人藏起来不让别人获得，而是复制修改，以及研究它的工作细节被禁止，这属于专制独裁，不属于私有财产的范畴。

nadebula前辈说的我可以理解，但您好像忽略了至关重要的方面。批判资本主义那些，我也要提醒一下，资本主义指资本主导社会经济和政治的意义，并无准确定义，不同经济学家有不同定义。有钱人是少数人啊！资本主导社会，那等于让少数资本家主导社会，这就属于专制了。如果仅仅是贫富差距大，倒还不算什么，关键在于控制公司的人是资本家，他们在操纵着社会的重要组成部分（生产生活用品之类的），这无形中也是一种专制。RMS大神反对公司将股东利益放在首位，这合理——为何要牺牲广大员工（有时候可能还包括客户）的利益去维护一个人（或者少数人）的利益呢？这难道不是集权主义吗？（就算不是，那也是不合理的！）但这不是所谓的“私有财产权”问题。

最后再强调一下，最根本原因并不是因为私有软件的翻译很像私人软件而怕混淆。同时也请您不要把我和其他反对“私有软件”翻译的人和开源阵营的人扯在一起，至少我跟他们的理念并不一样。

**Comment by zerng07** [comment]
你好，我是繁中版的譯者。當初翻譯為「專有」的理由很簡單，就是想到所謂「專有名詞」的專有，在此代表「專門為某人或某組織持有」。專有二字在中文裡一直以來都是這個語義，所以我不覺得翻譯成專有有什麼問題。

此外，自由軟體也都採用著作權法來保障自由，所以任何自由軟體也都有其著作權人。唯一和專有軟體不同點在於：「人人都可以自由運用」這點。

備註：private software 在繁中裡我們翻譯為「私家軟體」。

**Comment by IFRFSX** [comment]
@nadebula @tonghuix @Hagb 

nadebula前辈的话我可以理解，我只是想提醒各位同胞们，为何很多人会把持有的财产权和专制的垄断权力分不清？其中一个重要原因在于“知识产权”这个混淆性的词汇被广泛使用和接受，它在散播一种误读——  [像专有版权和专利这样的垄断权和财产权是同一种东西。]  事实上真的是这样吗？至少我不信。商家们这么做是为了利益，哪怕牺牲民众的基本权利也在所不惜，但我们可不是这些专制狂，所以我们要分清，所以不能使用和“私有财产”挂钩的“私有软件”翻译结果。“专有”一词更合适。

**Comment by persmule** [comment]
在这一点上我完全赞同 @nadebula 的观点和立场，在此声明，如果执意将“私有软件”改为其他（如未经我们同意擅自合并相关修改），我们承诺一定会采取必要措施（有可能是极端措施）来捍卫自己的立场。

> 但我们可不是这些专制狂，所以我们要分清，所以不能使用和“私有财产”挂钩的“私有软件”翻译结果。

我们尊重你 @IFRFSX  的观点，但“不能使用……”这种说法，恰恰证明了你才是想要把自己的观点强加给我们的专制狂。

**Comment by IFRFSX** [comment]
@persmule @nadebula @tonghuix 

persmule 前辈，nadebula 前辈，对于公有制度，大家都知道苏联斯大林时期的时候就搞过禁止私人拥有生产资料的制度，这属于纯粹的经济公有制。这种反对私有制的观点用到自由软件的身上恐怕不合适。因为自由软件运动没有说私人不能独占持有代码，你可以私藏（而私藏恰恰是公有制的经济制度所不允许的，至少在当时是），要求的是发布后必须给出相关自由。如果你们真的想把反对私有制的观点用到软件上，请说“公有化软件”。

如果我们说反对私有软件，认为自由软件运动是反对私有制，别人认为我们和曾经的那些纯公有制度的公社的思想很像——谁私藏（私有制），谁就违规了。自由软件的思想根本上不一样，本书说得很明白——

>自由软件是指附带这样许可的软件，它允许任何人使用、复制和/或再分发，不论是逐字再分发还是再分发带有更改的版本，也不论免费还是有偿。特别地，这意味着源代码必须可获得。

这就很明显了，自由软件运动反对的是垄断和专制，而不是私人占有。并不是我强加观点给你们，而是为了避免这种危险的混淆，我才反复强调不能用“私有”词汇来描述非自由软件。我说这些是想劝各位，希望大家接受我的PR，更加看清专制和自私的区别，将我的修改合并到原书里面。

**Comment by IFRFSX** [comment]
@nadebula @persmule 

尽管不赞成，但我理解并尊重两位前辈的观点。至少我们都在抵抗数字世界专制权力的自由软件阵营，我不希望就因为就这么一点点小矛盾让对手占便宜，想必各位大佬前辈们也不希望吧。

**Comment by persmule** [comment]
> 并不是我强加观点给你们，而是为了避免这种危险的混淆，我才反复强调不能用“私有”词汇来描述非自由软件。我说这些是想劝各位，希望大家接受我的PR，更加看清专制和自私的区别，将我的修改合并到原书里面。

这仅仅是你自己的观点。我们立场不同，我也不认为你会接受我们的观点。同理，我们也不会接受你的观点和相关 PR。如果某些人一意孤行，我们将坚决反击。

> 我不希望就因为就这么一点点小矛盾让对手占便宜

这不是什么小矛盾，而是原则问题。在这一点上我们不会有任何让步，否则就是背叛我们自己。

**Comment by IFRFSX** [comment]
@persmule 我还发了个GPL的PR，里面没有提到proprietary的翻译，这一点我们没矛盾，总该没问题吧？

**Comment by persmule** [comment]
对事不对人。但我们每天都有工作要忙，不一定能抽出足够的时间校对。

**Comment by nadebula** [comment]
说到专制，不想想造成专制制度的根源是什么，不还是私有制吗。私有制在历史上曾经发挥过进步的作用，但仅限奴隶社会取代原始社会的时候。正是对生产资料的私人占有造成了阶级社会的各种不公，而资本主义将这种不公发展到了极致（参见马克思《共产党宣言》），到了该消灭它的时候了。另一方面，“专制”只是上层建筑，私有制是其经济基础。因此将 proprietary software 翻译为“私有软件”以批判其经济基础无疑更加有力。

关于某人争论公有制与自由软件精神不符，这是由于物质资料和软件代码完全不具备可比性，这在 RMS 的文章“Words to Avoid”中多次涉及。如果说公有制与自由软件精神不符，那么私有制和自由软件精神更加不符，仅仅因为“私人软件”（private software）这一种特例而全盘否定公有制并不可取，同样，仅仅因为 RMS 暂时不反对“私藏软件代码”而肯定私有制同样是错误的。我相信“私人软件”会随着私有制的消灭而自然消亡，如同它只是特定时期的一种权宜之计。（RMS 的 TEDx 演讲及其他演说中多次提到他希望黑客们分享软件，如同《自由软件之歌》那样。）

最后说一句，如果 Blug 能够将所谓官方翻译改进为“私有软件”，这将会是 Blug 对中文界软件自由运动的重大贡献，其指导意义绝对超出各位的想象。

**Comment by tonghuix** [comment]
提醒各位一下。毕竟这是要和 GNU 官网同步的，如 #166 之讨论，所以用语须尽可能保持一致。关于用语，我认为最好在 GNU 的 CTT 的邮件列表里面讨论，因为这样讨论好了，那么就可以为 @Hagb 正在做的同步工作减轻很大负担。邮件列表在此：https://lists.gnu.org/mailman/listinfo/www-zh-cn-translators

另外虽然我更倾向于“专有”，但不排斥另外的说法，在需要与 GNU 官网同步之前，这并不成为一个问题。还是那句话，统一用语显然对传播 GNU 和自由软件理念有很大帮助，这也是为啥 RMS 在此书里多次澄清和强调 free 的意义，以及特意写文章指出 Open Souse 用语的问题。给别人扣“专制狂魔”的帽子或者用“极端行为”来威胁，都不是理性讨论和解决问题的态度。

如果 @nadebula 和 @persmule 想要你们”私有“的版本，那么可以 Fork 以后自行分发，就如同 @IFRFSX 想要他自己更改过的封面一样。毕竟这是 GFDL 授予你们的自由。

**Comment by IFRFSX** [comment]
@nadebula 
专制的根源是独裁权力，比喻为类似秦始皇那样的封建专制恐怕更合适，自由软件和公有私有制度没关系（二者应该相辅相成），只和自由与压迫有关系。RMS大神不反对私下使用并不是暂时的，书里面说过，

>比如“Open Watcom”的许可证就不是自由的，因为它不允许将修改后的软件私人使用。幸运的是，只有很少一些程序使用这样的许可证。

>大部分软件并非如此生死攸关，拒绝将它对公众发布并不是特别地坏。因此，开发私人软件或者定制软件的实践与自由软件运动的原则之间并无冲突。

>事实上，当很多用户拥有某一程序的副本时，某些人确实会将其发布到互联网上，并且供其他人访问。我们认为人们应当如此，如果该程序确实有用。但这并非自由软件的强制要求。

这几句就已经说得很明白了，私下藏起来也是自由软件应当赋予你的自由，你拒绝发布也不是一件错事，如果不许私人使用，那是非自由的。所以您说的“我相信“私人软件”会随着私有制的消灭而自然消亡”应该并不是自由软件思想的本意。当然，如果您想要在一个共产主义社会里面发展自由软件，可以有这样的想法，但请不要添加到原版思想里面。

**Comment by IFRFSX** [comment]
@nadebula 还有就是，资本主义造成的不公其实仍然是独裁权力，这可跟占有生产资料没关系。关键是资本主义社会中是资本来主导社会经济和政治，有个很好的例子是美国——选举某些职位都要年薪达到一定程度，这就注定了少数富人才可以去主导政治。但是，如果抛开这一点（比如在我国），仅仅是私营企业占有生产资料，资本家并没有各种像在美国等资本主义国家那里的特权，那就不会有这种不公（政治独裁是另一回事）。

**Comment by persmule** [comment]
> 专制的根源是独裁权力……

> 还有就是，资本主义造成的不公其实仍然是独裁权力，这可跟占有生产资料没关系……

这仍然仅仅是你自己的解读（尽管在我看来片面至极，但反正我们都说服不了对方，也就不必浪费唇舌了）。我说过了，我们立场不同，我不认为你会接受我们的观点。同理，我们也不会接受你的观点和解读。

**Comment by IFRFSX** [comment]
@nadebula @persmule 在不久之前，我们有位老师告诉我们美国（作为资本主义国家）选举都要必须是年薪多少多少万（好像还有种族歧视性质的要求，具体忘了）。那么我来打个比方，美国某资本家因为有钱，获得了选举某政治职位的资格，提出了有利于资本家的法律，然后将不公的法律压在人民头上——人民因为年薪不高，无法去参与投票。但是在非资本主义（社会主义或者其他）国家，没有这条限制，那么人民也可以参与选举，直接将不公的法律否决掉。资本家依然占有那些资产，但是嫌弃它的不公政策的人可以选择其他企业工作，垄断集团无法推行不公之法，自然也就无法让劳动者或者用户集中在他们手中。

**Comment by tonghuix** [comment]
中国宣传的美国选举是资金游戏，这无法解释花钱少的多的特郎普却赢过花了大价钱的希拉里。这是中国为了抹黑民主政治而做的愚民宣传而已。

另外请不要将自由软件与专制的共产主义思想放到一起，这是极端错误的。也是国内外某些自称自由软件信徒，极端思想和极端行为的根源，比如前年 libreboot 那哥们所作所为。

**Comment by IFRFSX** [comment]
@nadebula @tonghuix 

我从不觉得资本/社会/共产  这三个主义能和民主/专制扯上边，这只是三种政治经济模式和社会框架罢了。资本主义可以独裁（例如法西斯主义），社会/共产主义也可以民主，这取决于具体怎么实施这些社会框架。

既然物质资料和软件代码没法比，那干嘛要把自由软件和共产主义相比呢？何况资本主义社会里面也可以发展自由软件。RMS前辈说得很清楚，禁止私人使用的许可证（RMS前辈提到的 Open Watcom 算一种）的软件是非自由的，所以自由软件运动发展成功后私人软件不会也不可能消亡。如果主要目的是要消灭私有制，提倡公有制，而不是为了消灭不自由的软件，让每个人都可以随便复制修改软件，那GNU的思想就不会是“自由软件”，而是“公有化/共产 软件”。

**Comment by IFRFSX** [comment]
还有，那个GPL的PR怎么就关了？我试过很多次，但是实在无法解决合并 commit 的问题，所以才罢手。但翻译本身，好像没什么问题吧？

**Comment by tonghuix** [comment]
这两个 PR 都是你自己关的啊，我还想问你为啥就给关了呢

**Comment by IFRFSX** [comment]
@tonghuix 我没关闭，只是用git提交了几次试验合并commit，它自己就莫名其妙关了。。。。。。可以重新打开么？

**Comment by IFRFSX** [comment]
@tonghuix 或者我重新发？

**Comment by nadebula** [comment]
软件自由运动和共产主义运动在“消灭私有制”的目标上是高度一致的，只是 RMS 本人没有意识到而已。如果 Blug 能够将软件自由运动上升到共产主义运动的高度（尽管看起来不太现实），则更是重大的贡献。

最后再多说一句，产生专制制度的根源正是私有制，不能离开经济基础空谈上层建筑。

**Comment by IFRFSX** [comment]
@tonghuix 有没有reopen PR的方法？

**Comment by IFRFSX** [comment]
貌似是因为刚才在弄commit的时候不小心把提交历史清空了，然后无法重新打开。。

**Comment by IFRFSX** [comment]
这样吧，我在本地有保存修改后的，那么我删掉重新fork应该可以。。。。。。

**Comment by tonghuix** [comment]
RMS 貌似非常反感将自由软件和共产主义混为一谈吧。

不要忘了我们的初衷是传播自由软件最本真，也是 RMS 本人真正的思想而不是**套了自由软件壳的共产主义**。只要他没说，或者哪怕暗示自由软件是一种共产主义，我们就不能过度解读，甚至强行附会。

**Comment by IceCatX** [comment]
@nadebula @tonghuix 然后我们继续讨论这个issue的问题！

我觉得tonghuix前辈说得很好，初衷是传播自由思想，而且 RMS前辈 也从没打算搞共产，另一方面自由软件和共产思想的目标根本上有不同，一个是反压迫支持自由，一个是反私有制支持公有。

**Comment by IceCatX** [comment]
还有就是，我看到有些地方竟然还把nonfree翻译成私有（例如非自由游戏的那篇），这是谁弄的？难道翻译这篇和那篇的前辈对“私有”一词喜欢到这种程度，以至于……

**Comment by IceCatX** [comment]
@tonghuix 修改错字的那个PR也重新发好了！这下commit就是一个了。这下我真的不敢再用git本地折腾rebase了，万一再一个不留神直接连这两个PR也莫名其妙close了，那就惨了！

**Comment by persmule** [comment]
> 我看到有些地方竟然还把nonfree翻译成私有
@IceCatX 就事论事。你要想修这个就为它单开一个 PR 和 issue。

**Comment by Hagb** [comment]
请各位都冷静一下……产生分支对大家都不好。

**Comment by Hagb** [comment]
@nadebula @persmule @tonghuix @IceCatX @IFRFSX 
这大概不是不可协调的。如果在同步问题上CTT同意保留不同的译名，主要矛盾就解决了。
@nadebula @persmule 可以于CTT的邮件列表 https://lists.gnu.org/mailman/listinfo/www-zh-cn-translators 进行讨论，或着让我或 @tonghuix 转达。

**Comment by nadebula** [comment]
回应某人：将 nonfree 翻译为“私有”其实没毛病，二者本就是同义词。尽管历史上曾经有过 semi-free（半自由）的软件分类，但是这一分类早已废弃，RMS 的“自由和非自由软件分类”等文中均有解释。

最后说几句关于所谓的“协调”的问题，我们代表 Blug 中的那部分自由软件爱好者，并不依附于所谓的 CTT。与之相反，我们是在帮助 CTT 改进过去的不足之处。仅仅因为所谓的“官方”、“主流”采用不同的译法，并不意味着我们必须无条件服从——那是典型的“一切经过统一战线”式的右倾投降主义。我对 CTT 只想说：Take it or leave it.

**Comment by Hagb** [comment]
@nadebula 抱歉。打错了。
“我并不没有任何让你们依附于CTT的意思”应为“我并没有任何让你们依附于CTT的意思”

**Comment by Hagb** [comment]
@nadebula @persmule CTT中并没有指定 “proprietary software”的译文，并且两种译名都存在在gnu.org，大概两种译名都是可以的。[GNU 术语中文参考翻译(草案)](https://www.gnu.org/server/standards/translations/zh-cn/dict.zh-cn.html)

**Comment by IFRFSX** [comment]
@nadebula @tonghuix @Hagb 
nadebula 前辈，对于您所说的，私有制导致专制，我想这可能错了——举个例子：苏联斯大林模式是专制的，同时也是公有制。正因为这种领导独裁决断的制度导致了它的专制，而资本主义的欧洲很多国家却是民主的。用在软件上，如果强制让每个用户必须将修改后的代码交给国家，那就是非自由的。禁止私下是使用而不分享是非自由的软件，自由软件社区鼓励分享，但却不强制分享发布（只是要求不能禁止复制修改并且把源码附带上），二者有很大区别。自由，你当然也有私藏的自由，对别人也没啥影响。但强制分享，性质就完全不一样了，那本身就是一种反自由的制度。

为什么我说自由软件无关公有私有财产？强制每个人都必须将劳动的产品卖给国家而不许卖给别人，这不是自由，这是中央集权。非自由则是你将产品卖给别人了但是却施加了不该施加的限制（遵守一些规则当然没问题，但前提是不可以影响自由）。农民将农产品往街上卖，这应该是属于私营的经济，但是却不影响自由——因为你买了一斤以后可以去用它做想做的任何事情嘛，农民又不会在麦子里面夹一张纸条，规定——“不许给别人吃”，“不许种植后拿出去卖” “只能你自己吃” 之类的限制。这样举例子是不是清晰多了？

对于 nonfree 的翻译，虽然和 proprietary 的含义一模一样，但毕竟不是严格对应的词汇，就像你把“不好”翻译为“坏”/“差劲” 一样，意思差不多，但不准确。

还有一件事，既然把我的PR逆转掉，那我只好在自己社区的资料站上发布了。

**Comment by tonghuix** [comment]
@Hagb 确实在 GNU 官网里这两个翻译都存在，虽然中文世界用“专有”的感觉稍多一点点。所以说这确实不是一个好解决的问题，需要和 CTT 一起来协调。如果能统一用语当然是最好。如果不行就这样同步过去也是可以的，但会造成用语混乱进一步扩大。

@nadebula @persmule 我们需要的是理性讨论一起解决问题，而不是压制异见排除异己，你把我从 FSFS-translator team 里移除丝毫无助于解决问题，更不能平息现有参与者对你的不满！热衷这种斯大林式的专制主义正是现在某些共产主义的通病。

我们需要的平等包容的讨论，最终形成共识，否则社区会很容易分裂，而现在最大的问题就在此。

**Comment by IceCatX** [comment]
@tonghuix 
https://movie.douban.com/review/4966720/

**Comment by IceCatX** [comment]
这篇文章，我不完全赞同，但是我觉得很有用。

**Comment by tonghuix** [comment]
GNU CTT 关于这个问题正在投票 https://lists.gnu.org/archive/html/www-zh-cn-translators/2018-09/msg00010.html

如果想参与投票，订阅 CTT 的邮件列表<https://lists.gnu.org/mailman/listinfo/www-zh-cn-translators>，然后在邮件主题里写明：```Re: [GNUCTT] 关于同步fsfs译文的问题```，然后在邮件内容里写明要支持翻译即可。

**Comment by IceCatX** [comment]
话说两位前辈如果翻译的是自己的文章，用你的个人立场当然没错——然这是RMS的文章，翻译的时候自然不可以用自己的立场而要使用RMS的立场。

某些人不是还觉得我认知浅薄么？那这次我就来点儿深刻的分析让你瞧瞧。

关于某前辈说的，RMS反对将公司股东的利益至于首位，说这个和反对私有制有关太牵强了吧！不该以少数人的利益为先本身就是常识。而至于“无人可以拥有”，结合现实情况就是自由软件每个用户都在拥有它——都可以按照自己是想法折腾，那么这种“拥有”肯定就不是个人或者某集团持有某东西的拥有，而是拥有权限，作为主人的“拥有”。如果这个“拥有”是指持有和私人财产权，反倒是非自由软件“用户不可以拥有”，因为你无法自由支配你的物品。倒是和某个极端版本的共产主义很像。

至于所谓的经济原因，

>最后再多说一句，产生专制制度的根源正是私有制，不能离开经济基础空谈上层建筑

一个有力的反驳——苏联斯大林模式不是私有制，可它就是专制。难道说斯大林把所有人民当XX一样圈养是民主吗？

我再怎么了解得少，我也知道，“专制”指的是制度，不是经济模式。独裁XX都是上级压下级，下级压平民，正因为平民没有办法决定不公制度的颁发，然后他们才制订了专制的经济模式压榨平民。如果平民有权阻止甚至否决不公之法的颁发，那自然是民主，也就可以搞出良好的经济制度。

我把话说到这份子上了，还有人说我认知浅薄学识差之类的，那我也只能无奈地耸耸肩咯。

**Comment by IceCatX** [comment]
对于一些社区成员所说的 “自由软件是共产主义” 这个观点，我觉得我们是时候停止争论了，直接一封邮件发过去问问RMS前辈就知道了。如果RMS愿意把 Free Software 改为 Communist software，那就让他们改啊，省得某些低等文明的杂碎整天指责我们自由软件阵营 “挂羊头卖狗肉” “明明是共产软件/公有化软件 却非要叫自由软件”。不过我更愿意相信RMS那么聪明的一个人，不会犯这样一个错误。自己折腾了那么多年的思想体系的深层精华怎么可能意识不到？

**Comment by tonghuix** [comment]
GNU CTT 关于这个问题的投票 https://lists.gnu.org/archive/html/www-zh-cn-translators/2018-09/msg00010.html 结果已经出来了。

**最终译为“专有软件”**讨论可以关闭了。

改这个用词应该是比较省事的替换，但是我建议在向 GNU 官网同步的时候一起改，这样校对起来也比较容易，如何？
