### ISSUE TITLE
翻译成专有软件比较好

### ISSUE THREAD

**Issue by hhiim** [beijinglug/fsfs-zh#224]
“专有”一词可以表示权利的专有，而且不会弄混淆，而“私有”表示的是类似私有财产之类的意思，我做了个自由软件，我没把它发布出去，我并没有错，因为我没有禁止任何一个拿到我这个软件的人自由的权利

**Comment by IceCatX** [comment]
是的。
RMS曾经说过，非自由的邪恶在于禁止协作和分享，而对于反对私有制之类的事情，跟这个无关。
至于反对某主义支持某主义什么的，我只能说，在某个主义下，人民用低微的工资买到可怜的一点点东西，但是毕竟你可以自由支配你买到的东西，专有软件世界连这都没有——你只能使用，不能干别的。

**Comment by tonghuix** [comment]
请到 #210 #200 中参与讨论。
