### ISSUE TITLE
审校《如何为你的作品选择一份许可证》

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#226]
#209 @mytbk 
我在为同步到GNU对《如何为你的作品选择一份许可证》进行审校，以下为目前我的疑问或建议：
### 1
> …… to make it easier for people to follow and **refer back to**.
> …… 让人们更简单地跟着做并可以**重新引用**。

我认为加粗部分应该为“参考”的意思
### 2
> These recommendations are for works designed to do practical jobs. Those include software, documentation, and some other things. Works of art, and works that state a point of view, are different issues;……
> 这些推荐是用于设计来做实用工作的作品的。**那些**包括了软件、文档和一些其他的东西。艺术作品、以及表达**一种**观点的作品，则不一样；……

我认为改为 “这些推荐是用于**那些被**设计来做实用工作的作品的。**这**包括了软件、文档和一些其他的东西。艺术作品、以及表达观点的作品，则不一样；……” 可能更好。
### 3 
> They do not address the issue of combining existing material under different licenses.
> 它们不**用**解决结合已有不同许可证的材料的问题。

我认为应该把粗体部分（“用”）删去或者意译为“能”
### 4
> …… you should usually release your modified versions under the same license as **the original work**.
> …… 你通常应该在和**原有工作**相同的许可证之下发布你修改过的版本。

我认为粗体部分译为“原作品”可能会更好

**Comment by IceCatX** [comment]
4是经常会发生的错误，我之前也不慎犯过这个错误，也多亏了@tonghuix 提醒我。我觉得你完全可以直接发送PR改掉它。

**Comment by Hagb** [comment]
@IceCatX 我还是等 @mytbk 确认过之后再发PR吧。

**Comment by mytbk** [comment]
我觉得可以。
当初 @tonghuix 说过这篇文章我翻译得很糟糕......

**Comment by Hagb** [comment]
### 5

> One case where using a different license can be **justified** is when you make major changes to a work under a noncopyleft license.
> 一种可以**支持**使用不同许可证的情形，**是当**你在非 copyleft 许可证下的作品上做出了主要修改。

改为“一种可以**合法**使用不同许可证的情形**是**，你在非 copyleft 许可证下的作品上做出了主要修改。”可能会更好。

### 6

> **For honesty’s sake**, show explicitly which parts of the work are under which license.
> **安全起见**，请明确地表示哪部分的**工作**是在哪种许可证之下。

1)for honesty's sake 是什么意思，为何翻译成“安全起见”？
2)建议“工作”改为“作品”。

### 7

> We recommend different licenses for different projects, depending mostly on the software’s purpose. In general, we recommend using the strongest copyleft license that doesn’t interfere with that purpose.
> 对不同的项目我们推荐不同的许可证，主要依据软件的目的。通常来说，我们推荐使用最 copyleft 而不影响**那种**目的的许可证。

1)“主要依据软件的目的”前加“这”会不会更好？
2)删去粗体部分“那种”或许会更好。

### 8

> For those programs, we recommend the Apache License 2.0.
> 对**那些**程序，我们推荐 Apache 2.0 许可证。

前文刚说了小程序的问题，感觉按照中文习惯加粗部分大概为“这些”会好些。

### 9

> This doesn’t make the software immune to threats from patents (a software license can’t do that), but it does prevent patent holders from setting up a “bait and switch” where they release the software under free terms then require recipients to agree to nonfree terms in a patent license.
> 这并不会让软件避免来自专利的威胁（一个软件许可证是做不到的），**但它避免了专利持有者以自由为障目发布软件，**这种情况下专利持有者会相当于做了一次“诱导转向”，然后要求接受者同意专利证书中的非自由条目。

“它避免了专利持有者以自由为障目发布软件”貌似是原文没有的，并且“以自由为障目”怪怪的，（障目”是动词吧）。这里该怎么改呢？

**Comment by tonghuix** [comment]
障目确实有点怪怪的，本来是想表达以XXX为借口或者托辞。

**Comment by Hagb** [comment]
或许可以使用“打着自由的幌子”？

**Comment by IceCatX** [comment]
@tonghuix @hagb 

我们可以将其改为“以自由做为掩护”，因为专利持有者明明可以作为专有许可证发布，却用自由软件许可证来发布软件，却保留专利权，“以自由为借口”搞得好像自由是发布软件的必要条件一样，实际情况却是以专利软件来冒充自由软件。

然后再就是，障目好像确实是描述一个动作的，而不是一个事或者物。掩护一词也可描述那些作为遮挡物的事物。

**Comment by IceCatX** [comment]
@Hagb 

6. for honesty's sake

    honesty正直; 诚实，真诚
    sake缘故; 理由; 日本米酒; 目的

改为“为了诚实的原因”可以吗？

1. refer back to

    refer back to
    英 [riˈfə: bæk tu:] 美 [rɪˈfɚ bæk tu]
    将…转回;重新提及，查阅

改为“查阅”或者“参考”

这样可以吗？

**Comment by Hagb** [comment]
@IceCatX 可能是这个意思，但是从上下文来看还是觉得怪怪的。

@tonghuix 我因为业余时间和语言水平，这个审校会比较缓慢。

**Comment by IceCatX** [comment]
@tonghuix 行

**Comment by Hagb** [comment]
关于“For honesty's sake”，GNU CTT 里 Monnand 的解释： （http://lists.gnu.org/archive/html/www-zh-cn-translators/2018-10/msg00005.html）

> 针对这句话，我的建议翻译是：请如实标明作品中各部分分别采用的是何种许可证。
> 
> 具体理由：
> 
> For something/someone's sake 在有些语境下是一种带着情绪的强调句式。最直白/常见的： For God's sake 。这种表述往往是想表明某种底线。中文里类似的语境下，可能会说“不看僧面看佛面”之类的话。表示告诉对方，哪怕你不按常理办事，至少也要有条底线。
> 
> 我们可以看整段文字：
> 
> If you choose to release your contributions under a different license for whatever reason, you must make sure that the original license allows use of the material under your chosen license. For honesty's sake, show explicitly which parts of the work are under which license.
> 
> RMS 在这段中说的是：把自己对别人作品的修改换个许可证再发布。法律上讲，这个操作学要遵循两个条件，第一，需要保证两个许可证兼容。第二，绝大部分情况下需要注明哪部分采用的是什么许可证（除非作品是公共域或许可证明确说明不必如此）。对于第二条，本身是个法律上需要遵守的原则。但是 RMS 说的是 For honesty's sake，就是说“你哪怕无视法律也要对得起良心”这么个意思。说得是起码要有个底线。
> 
> 中文里，要表达这个意思很难像原文那样简短又符合日常用语习惯。所以没必要刻意去把每个词都对应地翻译出来。

**Comment by tonghuix** [comment]
那么翻译为“至少从良心上来讲，……”如何？

**Comment by Hagb** [comment]
粗体部分为修改的内容

### 10

> Unlike the first case, where the library implements an ethically superior stan-
> dard, **here adoption for its own sake** will not accomplish any special objective
> goal, so there’s no reason to avoid copyleft entirely. ……
> The Lesser GPL was designed to fill the middle ground between
> these cases, allowing proprietary software developers to use the covered library,
> but providing a weak copyleft that gives users freedom regarding the library
> code itself.
> **不像第一种情形，在那种情形中**这个库实现了一个伦理上更优秀的标准，在这里**让他自身承受风险**并不会达成实际好处，所以没有理由完全避免 copyleft。……**较为宽松的 GPL** 是设计于填补这些情形中间地带的，允许私有软件开发者使用其保护起来的库，但考虑到库代码本身，提供了**一些**给用户自由的 copyleft。

建议改为：

> **在第一种情形中**库实现了一个伦理上更优秀的标准，**但在这里不像第一种情形**，**库的广泛使用**并不会达成实际好处，所以**完全**没有理由避免 copyleft。……**较为宽松的 GPL（LGPL）** 是设计于填补这些情形中间地带的，允许私有软件开发者使用其保护起来的库，但考虑到库代码本身，**LGPL** 提供了给用户自由的**弱** copyleft。

### 11

> The AGPL’s requirement doesn’t address the problems that can arise **for users** when they **entrust** their computing or their data **to** someone else’s server.
> AGPL 的要求没有解决当 _用户们_ 信赖其计算或者发送数据到别人的服务器时，会产生的问题。

建议改为：

> 对于 _用户们_ 而言，AGPL 的要求没有解决当**他们委托其计算或者数据给**别人的服务器时，会产生的问题。

### 12 

> It’s a strong copyleft
> license for educational works, initially written for software manuals, and includes
> terms which specifically address common issues that arise when those works are
> distributed or modified.
> 对教育型工作，这是个很强的 copyleft 许可证，最早为软件文档而编写，**并包含特别说明，即**当这些作品被分发或修改时的常见问题。

terms which.... 感觉怎么翻译都不如意译通顺。
建议改为：

> 对教育型工作，这是个很强的 copyleft 许可证，最早为软件文档而编写，**并特别说明了**当这些作品被分发或修改时的常见问题。

### 13

> For short, secondary documentation works, such as a reference card, it is
> better to use the **GNU all-permissive license** ……
> 对于短的、次要的文档工作，例如参考卡片，最好使用 **GNU 宽松的许可证**……

GNU all-permissive license 不是 “GNU 宽松的许可证” 吧，后者是 LGPL 吧？（不过我不知道前者该怎么翻译）

### 14 

> This section discusses all other works for practical use that you might include
> with software. **To give you some examples, this includes** icons and other func-
> tional or useful graphics, fonts, and geographic data.
> 这段讨论你会包括在软件中的所有其他实用 **工作**。**给你一些例子，这包括** 图表和其他功能性或有用的图像、字体和地理数据等。

其中 To give you some examples 意译为“例如”或许会更好。
建议改为：

> 这段讨论你会包括在软件中的所有其他实用 **作品**。**例如** 图表和其他功能性或有用的图像、字体和地理数据等。

### 15

> There is no problem in doing so with the licenses we have rec-
> ommended: GPLv3, LGPLv3, AGPLv3, and GPLv2 can all be applied to any
> kind of work—not just software—that is copyrightable and has a clear preferred
> form for modification. 
> 用我们推荐的许可证这样做不会有问题：GPLv3、LGPLv3、AGPLv3 和 GPLv2 都可以用于任何类型——不只是软件——**受版权保护并为修改版澄清首选的形式**。

这里破折号后的“that is ……”应该是 “any kind of work” 的定语，意思应该是说只需要能受版权保护（copyrightable）……
但是这里 “clear preferred form” 中 “preferred”是什么意思？

### 16

> Using the same license as the software will help make
> compliance easier for distributors, and avoids any doubt about potential com-
> patibility issues. Using a different free license may be appropriate if it provides
> some specific practical benefit, like better cooperation with other free projects.
> 使用与软件相同的许可证 **对分发者而言会让合规性更简单**，并可以避免任何潜在的兼容性问题。果提供了一些特别的实用的好处，比如和其他自由项目更好地合作，使用一个不同的许可证可能是合适的。

建议改为：
使用与软件相同的许可证 **会让分发者更容易遵守规定**，并可以避免任何 **对** 潜在的兼容性问题 **的顾虑**。果提供了一些特别的实用的好处，比如和其他自由项目更好地合作，**那么** 使用一个不同的许可证可能是合适的。

**Comment by Hagb** [comment]
@tonghuix 您看看 CTT 邮件列表的讨论，确定“For honesty's sake”怎么处理吧？
现在可以说已经审校完了。

**Comment by Hagb** [comment]
还有第 15 点那个prefferred……感觉所有义项放进去都觉得别扭。

**Comment by Hagb** [comment]
已同步至 gnu.org/licenses/license-recommendations.html
