### ISSUE TITLE
错误：译者注

### ISSUE THREAD

**Issue by chenguokai** [beijinglug/fsfs-zh#227]
在1.2.10章节中有一段脚注：
在本文中采用**云南大学的贾星克、李极光二位教授**的 “左版” 的译 法——译者注。

经查，原文献应为两位作者发表于云南师范大学学报的《论自由软件运动》，但在原文献中贾星克为云南师范大学副教授，李极光为四川省中国国际旅行社经济师，均非云南大学教授。其中，经过进一步查询，贾星克为云南大学毕业生，李极光信息较少，毕业院校未知。

因此，当前版本的表述不够合适，希望修改。

**Comment by persmule** [comment]
已着手订正，感谢指出！

**Comment by tonghuix** [comment]
考据派！点赞！

**Comment by chenguokai** [comment]
😂主要是我之前看过这篇文章，对作者有点印象，看到这里感觉有点不对，就去确认了一下。
