### ISSUE TITLE
对“专有软件”的投票结果表示遗憾

### ISSUE THREAD

**Issue by nadebula** [beijinglug/fsfs-zh#231]
所谓的“公投”已经有了结果，但是，Blug 社区仍有改正此错误的机会和义务。如同我在之前的 issue 中所说，“私有软件”才是最深刻的批判，也是符合 RMS 原意的。仅仅因为所谓的“主流”（不论出于何种原因或者动机）提议所谓的“专有软件”，并不意为着 Blug 也必须无条件服从，这是“一切经过统一战线”的右倾投降主义，也是屈从于社会惯性的表现。

我在之前的 issue 中已经说过了自由软件运动是要批判产生私有软件的经济基础——私有制。只有对经济基础进行揭露和批判才是最有力的。相反，“专有软件”一词反而具有误导性，即使人误认为自由软件运动是在反对专制。但是千万别忘了，左版本身就是专制（针对私有化行为的专制），若非如此不能保证自由。包容型许可证就是最好的例子。

最后，衷心希望 Blug 能够改正这个错误，即使这与所谓 GNU 官方的“主流”意见不符，大不了就不在 GNU 官方发表呗。RMS 在 X Window 陷阱一文中说得很清楚，如果能够看轻所谓的名誉和流行度，就能变得更加强大。我还是不愿意看到 Blug 堕落为一个连“私有”二字都没有底气说出来的社区。（可话说回来，羞于正视“私有”，到底是害怕什么呢……）

**Comment by Hagb** [comment]
有一点不解的是，为什么两位前辈不参加投票（或者说是“所谓的公投”）呢？
最终的结果也就“专有软件”两票，其他0票……

**Comment by tonghuix** [comment]
为何你们不参与投票呢？本来我对这俩词都不反感，无非就是确定一个能更统一而已。

> 因为这项所谓的投票毫无客观公平性可言，所以我们不会承认这项所谓的投票及其所谓的结果，也决不考虑更改“私有软件”这一用词。

@persmule 你觉得这投票的客观公正性问题出在哪里？

**Comment by nadebula** [comment]
因为我知道所谓的投票的结果一定是令人遗憾的，所以没有参与的必要。

既然某人说对“私有”和“专有”两种说法都不反感，那么为何不统一为正确的“私有软件”？在之前的 issue 的辩论中，支持“专有”的一方似乎只能拿“私人软件”这一特例来说事。这也印证了某人对此必然抱有严重的偏向性而绝非口头上所说的“都不反感”，所谓“投票”只是为了达到目的所采取的某种形式。别忘了之前有人曾经说过所谓“官方”的主流意见是“专有”，而这次“投票”又是通过所谓的“官方”平台进行的，这其中能有多少客观中立性可言？

**Comment by persmule** [comment]
这种“皇族内阁”式的所谓的投票我们为什么要参与呢？

**Comment by tonghuix** [comment]
怎么“皇族内阁”了？GNU CTT邮件列表不是封闭的，只要订阅即可发邮件啊。而且一直是开放订阅的啊。

**Comment by nadebula** [comment]
哈哈，我这帖子算 Trolling，那么之前某人污蔑社会主义为“某大锅饭的平均主义”以及注册马甲重复发帖算什么？感谢阁下让我见识到了什么叫所谓的“客观中立性”。

**Comment by tonghuix** [comment]
因为你只是在表达情绪，和无谓的说辞，而不是声明观点，提出有价值的建议或意见。这和 trolling 无异。

上一个这个干 issue，因为 issue 已经关闭就懒得再打标签了。

**Comment by nadebula** [comment]
回复某前任负责人：我一直在声明观点，也一直在提出有价值的建议。我长期以来的建议就是敦促 Blug 以及所谓 GNU 官方汉化组改正“专有软件”这个错误，不过遇到了前所未有的困难，总是有些人以各种方式（包括所谓的“投票”）坚持过去的错误，哪怕已经到了理屈词穷的地步。如果谁认为这种事关立场的建议不属于“有价值”的话，我也无话可说。

**Comment by Hagb** [comment]
@nadebula 既然要“敦促 Blug 以及所谓 GNU 官方汉化组改正错误”，那么为何不做些实际的行动 (比如参加投票，事实上如果两位前辈参加投票的话，现在的结果就不一样了吧) 呢？
另外，有一个疑问，“私有”能否涵盖仅允许非商业性（noncommercial）许可证下的软件呢？

**Comment by persmule** [comment]
@Hagb 由某人单方面擅自发动，且总共只有两人参与的投票能有啥说服力？况且有人在其他 issue 干过使用多马甲发帖的事，谁能保证他不会再干……

**Comment by Hagb** [comment]
@persmule 
该投票**仅仅是决定 GNU CTT 内今后关于该词的用语**。至于其他地方是否使用哪种翻译，这个投票没有也不会有任何效力。
我个人认为，RMS 和 GNU 有它们自身局限性，其他人也无需完全按照“GNU官方的说法”。我个人建议：既然在 fsfs-zh 中无法取得统一的意见，那么即使将译文同步到 GNU，fsfs-zh 也保持现状（即，“专有软件”和“私有软件”并存）。

**Comment by IceCatX** [comment]
@persmule @nadebula @tonghuix 

几位前辈，你们好！

你们说的那个改马甲发帖的事情其实是你们误会了，那个hhiim是我的一个朋友，他也是自由软件支持者，并且也更喜欢“专有”这个翻译，所以我和他一人发了一个帖子阐述理由。你们怎么会误解为我开小号发的呢？明明他说话的语气什么的完全不一样。
在这贴一下他的原话：

```
“专有”一词可以表示权利的专有，而且不会弄混淆，而“私有”表示的是类似私有财产之类的意思，我做了个自由软件，我没把它发布出去，我并没有错，因为我没有禁止任何一个拿到我这个软件的人自由的权利
--
```

**Comment by IceCatX** [comment]
前面有人提到不能脱离经济基础空谈上层建筑，没错，正常情况下是应该让经济基础来决定上层建筑，但同一个基础建筑也不一定只能有一种上层建筑，就好比我挖了一个地基，这个地基不是很好，所以我建造的建筑不可以超过10t的重量，长宽不可以超过5米，但我将它搞成尖头或者圆头或者内部桌椅，设备的摆放，以及里面的电线布线什么的总不会受什么限制吧，我这样比喻够清晰吗？

造成专有软件问题的主要不是私有制，而是垄断和集权。copyleft严格来说不属于专制，因为根本没有限制你随便造个修改版去分道扬镳，只是除了已经规定的例外以外，必须用同一个许可条款而已。只能说自由度足够高，开放度不很高而已。自由软件精神强调的并非公有制，而是自由和没有限制，它是一场人权运动而非共产主义运动。

并且RMS如果真反对私有制的话，干嘛不直接把理论的名字设定为“公有化软件”或者“共产软件”呢？RMS前辈他们不可能奋斗了几十年还不知道自己理论的本质；并且“专有的”一词本身就是proprietary在词典上的标准翻译。

最后我想问一下某位前辈，为何您总给GNU官方翻译组前面加上“所谓的”三个字呢？GNU CTT是GNU 官方的翻译团队！对于几个月前您在另一个issue的那句“RMS没有意识到”，自由软件这一概念的解释权完全归以RMS前辈为首的FSF和GNU（因为是RMS提出的），所以这样说恐怕不太合适……

**Comment by IceCatX** [comment]
RMS所反对的是软件复制修改权（即所谓“所有权”），“专有”或者“专权”才是最贴切的。并且FSFS的最后一章RMS已经表明了他对民主的支持（并且还给出了制止专制的关键——揭露）。Proprietary原意指的就是专有权，专利，独家制造的含义，非自由软件的性质就在于此。“私有”（private）对应的是私人的; 秘密的，—— 根据词典上的造句，甚至在英语里面这个词是表示“私立医院” “私立学校”的“私立”（仔细想想，这不是自由软件环境内很多人都在做吗？造个某款在自由软件的非官方的修改版，然后私自发展，这个完全合法并且合理），没有“所有权”的含义，这样肯定不贴切。RMS既然选择了 Proprietary 而非 Private ，自然不会赞成“私有”这一说法的（如果他熟悉这几个中文词汇）。我在此劝告一下各位朋友们，我不否认共产主义有一定的先进性和合理性，但请不要因为喜欢共产主义就把看着像的东西往一起放。

执意要用自己的立场去扭曲RMS的立场，这样真的好吗？更何况起什么名字并非最要紧的事情，关键在于自由软件的精神和价值观是否能让广大人民群众去支持。有人说我对自由软件的宣传是只想着出名，这是一种恶毒的诽谤！现在的自由软件世界，知道的人很少，大家还是容易受到那些独裁厂商的迷惑，这样的被洗脑者我见过几个，可以用“没救”二字来形容了。至于比较奇葩的那些觉得自己比RMS还要高明，甚至不愿意肯定RMS对自由软件精神的解释权，我们又能怎么办呢？

**Comment by tonghuix** [comment]
> @persmule
> 该投票**仅仅是决定 GNU CTT 内今后关于该词的用语**。至于其他地方使用哪种翻译，这个投票没有也不会有任何效力。
> 我个人认为，RMS 和 GNU 有它们自身局限性，其他人也无需完全按照“GNU官方的说法”。我个人建议：既然在 fsfs-zh 中无法取得统一的意见，那么即使将译文同步到 GNU，fsfs-zh 也保持现状（即，“专有软件”和“私有软件”并存）。

这里还是会保持和 GNU CTT 的同步的，因为向 GNU 同步的目的是为了合法的出版发行（RMS 要求的必须先向 GNU 官网同步，才能公开发行）。相关讨论见 #209 #146 

各位可以按喜好保留符合自己需要的版本，比如 @IceCatX 保留的自制封面的版本。

**Comment by nadebula** [comment]
我对某 GNU CTT 官方负责人允许 fsfs-zh “维持现状”表示赞赏。不过我会于近期整理一些关于为何“私有软件”是正确的解读而“专有软件”的矛头指错并且具有误导性的论述。（其实之前已经零散地发表了很多了，在这里再次指出，RMS 对“自由私人软件”的中立态度不能成为为“私有软件”以及私有制辩护的理由。）

我对某前任负责人为了出版发行而罔顾重要贡献者的观点立场强行同步表示坚决反对。（为什么一定要出版发行呢？RMS 不止一次地说过，看轻所谓的知名度和流行度，就能变得更加坚定。）

**Comment by Hagb** [comment]
我的发言仅代表个人… 不代表 GNU CTT

**Comment by nadebula** [comment]
仅代表个人建议和意见，也同样值得赞赏。如果其他 GNU CTT 成员也像某位前任负责人一样独断专行，我同样会和他（们）斗争到底。

**Comment by IFRFSX** [comment]
@nadebula @Hagb @tonghuix 

如果RMS大神真要反对私有制，他就不会使用“Proprietary”这个词。私有制真正的对应词汇是“Private ownership”。如果某些人不信，可以自己发邮件问问RMS到底是不是打算搞共产——如果是（我是说假如！！），那他完全可以直接把“Free Software”改为“Public Wonership Software”，然后将真正的自由支持者（Free Software）单独划分一个阵营，这样也省得某些 lu 瑟 er 整天风言风语诋毁 RMS “挂羊头买狗肉” 了。如何？

专制和自由完全是水火不容的，Copyleft不是也不可能是专制的，否则那左版自由软件也配不上“自由”之名了。

**Comment by IFRFSX** [comment]
proprietary
n. 所有权；所有人adj. 所有的；专利的；私人拥有的

**Comment by IFRFSX** [comment]
@persmule @nadebula @Hagb @tonghuix 

http://www.sohu.com/a/161834924_611098

关于版权或者专利是否和私有制有关，这篇文章写得比较详细，财产权（当然包括生产资料）和所谓的“知识产权”这个混乱的概念（这里指的应该是版权或者专利）是完全相对立的，所以反对版权或者专利的过度限制和膨胀和反对私有制完全不是一个性质。

关于翻译结果的问题，这涉及的应该不是个人立场的问题，而是我们到底反对的是什么，支持的是什么。还请各位能仔细再考虑考虑。

**Comment by IFRFSX** [comment]
最后，@tonghuix @Hagb 目前为止我没有再次发现FSFS有错字，我自己的保留版本除了封面不一样，将私有换为专有（除了最后一张的“私有目的”的“私有”指的是公司自己的意思，不是专有，所以没动），其他基本一致。如果你们希望给这本书换个封面，我可以再为你们做其他颜色的封面（只要我有空）。
