### ISSUE TITLE
多彩封面？

### ISSUE THREAD

**Issue by IFRFSX** [beijinglug/fsfs-zh#235]
![cover_black](https://user-images.githubusercontent.com/34205903/49935797-435a3880-fefc-11e8-8b7c-e06448e1c193.png)

![cover](https://user-images.githubusercontent.com/34205903/49935835-5a008f80-fefc-11e8-8540-002354a65c2f.png)

不久前我有这样一个想法：如果BLUG或者我（或者我社区的其他伙伴？）想要把这个书当作纪念品给参与某些活动的客人，那么多种封面是否更吸引人？
今天我做了第二个修改版封面，两个都是GIMP做的。
如果要XCF工程文件，请发送EMail到1079092922@qq.com，只要我有空闲时间，就将XCF通过附件发回去。图片我仅保留署名权。

**Comment by tonghuix** [comment]
额，原图是 SVG 的。你用 GIMP 修改挺费劲的吧。

**Comment by IFRFSX** [comment]
我修改的是doc文件夹里面的png文件，目前我还没研究svg格式矢量图的制作。但是这不代表我不会搞复杂的，是因为没有必要复杂，而且我做复杂图有时候有可能会把图搞得五颜六色，别到时候反而就不像是哲学书了。

**Comment by IFRFSX** [comment]
@tonghuix 回复你在那个PR给我发的错句：我不是很喜欢用commit（不要问我为何），不叫所谓的“无知当个性”，世界上根本不可能真正存在的这种人。人各有喜欢和不喜欢的东西，请不要认为别人和你的喜好一样。

**Comment by persmule** [comment]
@IFRFSX 
> 回复你在那个PR给我发的错句

在哪儿发的请到哪里去回复。
> 我不是很喜欢commit

连 commit 都不“喜欢”用就别来这儿帮倒忙了。

**Comment by IFRFSX** [comment]
@persmule 我只是觉得其功能有不足之处，并且提出一点看法，怎么就成了为所欲为了？更何况，我最后还不是把github的用法学会了。你不喜欢我的论点，我可以删掉，但请不要说伤人话可以不可以？
