### ISSUE TITLE
审校《应用自由软件判断准则》

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#236]
#209 
以下为我的一些疑问

**目前以下第 8 点还未解决。** 

### 1

> A nonfree program is an injustice.
> 一个非自由程序是一种不公。

此处的原文应该是类指。所以我认为译成“非自由程序是一种不公”或者“非自由程序是不公的”会更好。

### 2

> To distribute a nonfree program, to rec-
> ommend a nonfree program to other people, or more generally steer them into a
> course **that leads to using nonfree software**, means leading them to give up their
> freedom.
> 发布一个非自由程序、向他人推荐非自
> 由程序、或是更为普遍地将它们引入课程**以引导人们使用非自由软件**,以
> 上这些行为意味着引导人们放弃自己的自由。

加粗处的原文是course的定语，说的是 使用非自由软件 成了这个课程的结果……而“以”字在现代汉语貌似没有表结果的意义，而在文言文中有。所以我认为此处“以”字不妥，易引起误解，建议改译。

### 3 

> A nonfree system is an injustice……
> 一个非自由操作系统是一种不公……

同上第1条

### 4 

> Supporting a free program on that system does not **compound**
> the injustice.  
> 支持该非自由操作系统上的自由软件并不**构成**这种不公。

“compound”一词有“To worsen a situation ”的意义，而“To compose; to constitute.”的意义是 obsolete 的（[https://en.wiktionary.org/wiki/compound](https://en.wiktionary.org/wiki/compound)）。所以我认为这里应该译成“加重”或者类似意思的词。

### 5

> For instance, we choose LibreOffice over OpenOffice because 
OpenOffice suggests use of nonfree add-ons, while LibreOffice **shuns** them.  
> 由于后者提示用户使用非自由扩展,而 LibreOffice 则**拒绝**它们

“shuns”意义没有“拒绝”那么强烈（[https://en.wiktionary.org/wiki/shun#English](https://en.wiktionary.org/wiki/shun#English)），而“拒绝”容易让人理解为 LibreOffice 和 GCC 一样不允许非自由扩展（我不知道 LibreOffice 是否是这样，但是原文似乎只是指 LibreOffice 的做法和 OpenOffice 不同）。

**Comment by Hagb** [comment]
@tonghuix 
在2中，其实我想说的也就是这里的译文有表目的的意思，会不会偏离了原文的意思。感觉这（即“引导人们使用非自由软件”）在原文中这不一定是指目的……
  
> 4译成“进一步恶化”比较好吧？

具体是？

> 确实没有“拒绝”那么强烈，译为“避免”或者“一律不接受”。

我担心的是，这里（原翻译）表达出来的含义是： LibreOffice 的情况和上文说的 GCC 一样，而“一律不接受”可能也有这样的问题。（我不知道是不是这样，但是感觉英文原文中没有这种意思。如果事实是这样的话，原翻译也是恰当的）

**Comment by IFRFSX** [comment]
@hagb 我来说说我看法。
5你可以翻译为：然而Libreoffice避开（或者回避）了它们。
2可以是：或是更为普遍地将它们引入一个课程以引导人们去使用非自由软件

可以吗？

**Comment by tonghuix** [comment]
我对4的翻译是
>支持该非自由操作系统上的自由软件并不会**进一步恶化**这种不公。

对于5，要不就稍微弱化一下语气：由于后者提示用户使用非自由扩展,而 Libreoffice并不会这样做。

关于2的翻译，我个人偏向觉得 @IFRFSX 这里的说法更好。

**Comment by Hagb** [comment]
### 6

> Some distros install programs from binary packages **that are part of the distro**
> 某些发行版通过作为其发行版一部分的二进制包安装软件

下文接着说到一个发行版“包含”某个软件包的问题，所以我（加上常识的判断）认为这里加粗部分修饰 “programs” 而不是 “binary packages”，可改为“某些发行版从二进制包安装作为其发行版一部分的软件”

### 7

> It can also have code in true **read-only memory.**
> 它也可能在真正**只读的内存**中拥有代码。

这里加粗处应是“只读存储器”（[https://zh.wikipedia.org/wiki/%E5%94%AF%E8%AE%80%E8%A8%98%E6%86%B6%E9%AB%94](https://zh.wikipedia.org/wiki/%E5%94%AF%E8%AE%80%E8%A8%98%E6%86%B6%E9%AB%94)）
另外（不重要的），我个人感觉这里“拥有”改为”有“、”存在“或”带有“可能稍微更好

### 8

> So our certification criteria cover only the code that runs
> on the computer’s main processor **and is not in** true read-only memory.
> 因此我们的认证准则仅仅覆盖那些运行在计算机的主处理器上**而**非真正只读内存中的代码。

除了与5一样的问题外，感觉这里原译文和原文表达的意思有点出入，我的想法是“因此我们的认证准则仅仅覆盖那些运行在计算机的主处理器上且储存在非真正只读存储器中的代码”

### 9 

> **Often** the JavaScript code spies on the user.
> JavaScript 代码**通常**窥探用户。

此处我认为“通常”的程度应是“usually”，比“often”程度大，这里“Ofter”应是“常常”或者“时常”。

### 10

> Also, you will most often encounter nonfree JavaScript in other
> ways besides **following** our links.
> 此外，除了**追随**我们的链接，您会经常在其它网站遇到非自由的 JavaScript 代码

个人感觉“追随”一词实在不合适，此处加粗处建议意译，如将“追随”改为“进入”或“访问”，或者直接删去：
“此外，除了我们的链接，您会经常在其它网站遇到非自由的 JavaScript 代码”

### 11

> On principle, we do not link to such pages.
> 我们原则上不会链接这些网页。

此处“on principle”应是”从道德上考虑“这样的意思（[https://en.wiktionary.org/wiki/on_principle](https://en.wiktionary.org/wiki/on_principle)）。而”原则上“则是”in principle“，强调大体是这样。


### 12

> As new situations arise, the GNU Project and the
> Free Software Foundation will adapt our freedom criteria so as to lead computer
> users towards freedom, **in practice and in principle**.
> 随着新情况的出现，GNU 计划和 FSF 将会适配我们的自由准则，不论在**实践上还是原理上**，都将计算机用户引向自由。

此处个人认为加粗处译为”实践中还是理论上“更通顺（当然，两种译文意思是一样的）。

**Comment by Hagb** [comment]
@tonghuix 
6 “安装二进制的程序”和“从二进制包中安装的程序”是否是一个意思呢？
8 我认为原文是指 runs on the computer’s main processor **且(and)** is not in true read-only memory 是 code 在这些规则的覆盖下。
10 那么这儿该译为什么（或者是什么意思）呢？（个人感觉“关注/订阅我们的链接”不是很合文意和常识）

**Comment by tonghuix** [comment]
6 这是我翻译错了，确实应该是从二进制包里安装程序。

8 我觉得原翻译是对的。这个代码只包括能运行在计算机主处理器上的，但不包括在只读存储器里的。我想这可能是因为只读存储器比如 EEPROM 里存的代码如果完全没可能调用它，那么它就会一直呆在那里，而不会在处理器里被执行，因此也就不会有是否自由的问题。

10 “关注这个链接里的文章”你觉得如何？

**Comment by Hagb** [comment]
@tonghuix 我是这样想的：
某一些只读存储器的代码是在主处理器中运行的，但因为它储存在只读存储器，不可修改，所以看作等同于电路吧？（所以我想这就是为什么要强调“真正的”）
原翻译大概没有把 “运行在主处理器上” 和 “并非储存在真正只读的存储器中”在这句话中的逻辑关系说清楚…我认为这是一个“且”的关系：既要运行在主处理器上，又要在非只读存储器中，才会被规则覆盖。

**Comment by Hagb** [comment]
@tonghuix 
10 我还是觉得这里只是“访问”的意思，因为只要访问就可能受非自由JS的威胁，而订阅或者关注应该算访问的一种特殊形式吧……需不需要问一下GNU里的人呢？

**Comment by tonghuix** [comment]
10我觉得你这样比较通顺，而且也好理解。用词的细节而已，我觉得不用太纠结。

8 这个先留着如何？等更多人来帮忙如何？

**Comment by Hagb** [comment]
@tonghuix 
那就先留着 8 吧，是否需要再单独发一个issue？

**Comment by tonghuix** [comment]
我认为暂时先不用单独发 issue 了

**Comment by Hagb** [comment]
> > > In Applying the Free Software Criteria:
> > >  So our certification criteria cover only the code that runs
> > > on the computer’s main processor and is not in true read-only
> > > memory.
> > > 
> > > Does it mean that, not only does the code which the certification
> > > criteria cover run on the computer’s main processor, but also it is
> > > not in true read-only memory?
> > > 
> > > 
> > > Thanks!    
> > 
> > The read-only memory and the main processor don't contain the same
> > programs.
> > 
> > Here is how I understand this:
> > The main processor runs the complex programs you are used to, but
> > the read-only memory contains a specific program which operates a
> > piece of hardware. Since the memory is read-only, the program can't
> > possibly be modified. It is considered part of the hardware, that's
> > why free software criteria don't apply to it.
> > 
> >   
> 
> Thanks very much!
> 
> But I still don't completely understand. 
> Is the word "and" in "runs on the computer’s main processor and is not
> in true read-only memory" a logical conjunction (∧)?   

"And" means that both things are true.
  
> > The read-only memory and the main processor don't contain the same
> > programs.   

> Is there a case that, the code runs on the main processor and
> is in true read-only memory, or the code is not in true read-only
> memory and doesn't run on the main processor ? 
> How about these two kinds of code?  

I should have said "usually don't contain the same programs". I
wasn't thinking of code that runs on the main processor and is
stored in ROM. For instance some components may have non-modifiable
firmware which is used by the main program.

Firmware can often be modified. In this case, it is not in true
read-only memory. For example, SSDs can be flashed with new 
firmware. During the flashing process, a program is running on the
main processor.

The BIOS/UEFI firmware is another example of code that is not in
true ROM. I don't know exactly where this code runs at the very
beginning of the boot process, but if it runs on a special processor,
you have an example of code that is not in true read-only memory and
doesn't run on the main processor.
 
> (Sorry for my bad English :-) )  

I don't think it is bad.

Best,
Thérèse

**Comment by Hagb** [comment]
“"And" means that both things are true.”

**Comment by tonghuix** [comment]
所以应该翻译成啥？

**Comment by Hagb** [comment]
我认为要表达出”逻辑与“的逻辑关系……
原译文（”因此我们的认证准则仅仅覆盖那些**运行**在计算机的主处理器上**而非真正只读内存中的代码**“）似乎有点混乱：不管是在“而”和“非”之间断开还是把“而非”当作一个词，似乎都无法读出原文的意思。

**Comment by tonghuix** [comment]
我稍加意译一下如何：
因此我们的认证准则仅仅覆盖那些运行在计算机的主处理器的代码是不够的，还需要覆盖到只读内存中的代码

**Comment by Hagb** [comment]
真正只读的存储器中的代码视为硬件吧
我认为这里的意思应该是说认证准则覆盖的代码同时满足两个条件：
1、在主处理器上运行
2、不在只读存储器中

于 2019年3月2日 GMT+08:00 下午12:51:01, Tong Hui <notifications@github.com> 写到:

**Comment by tonghuix** [comment]
因此我们的认证准则仅仅覆盖那些运行在计算机的主处理器**和**非只读内存中的代码

**Comment by Hagb** [comment]
我觉得“运行在非只读内存中”的“运行”一词不妥。以及“read-only”建议译为“只读存储器”而非“只读内存”，以免歧义

**Comment by tonghuix** [comment]
因此我们的认证准则仅仅覆盖那些在计算机的主处理器上运行的代码，及非只读存储器中的代码

**Comment by Hagb** [comment]
emmm……

> "And" means that both things are true

如果“我们的认证准则仅仅覆盖那些在计算机的主处理器上运行的代码，及非只读存储器中的代码”的话，是不是就可能包括了那些只满足一者的代码……

**Comment by tonghuix** [comment]
哦对哦，你是说这是逻辑与的意思

我们的认证准则仅仅覆盖那些可以在计算机的主处理器上运行且存储于非只读存储器中的代码

**Comment by Hagb** [comment]
我认为这是可以的

**Comment by Hagb** [comment]
那次修改时，我改的版本好像就是用“且”。这个 issue 是不是可以关闭了？
