### ISSUE TITLE
关于ethics（“伦理”或“道德”）及其派生词的翻译

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#237]
[https://en.wiktionary.org/wiki/ethics](https://en.wiktionary.org/wiki/ethics)：

> 1. (philosophy) **The study of principles relating to right and wrong conduct.**
> 2. Morality.
> 3. The standards that govern the conduct of a person, especially a member of a profession.

> Although the terms ethics and morality are often used interchangeably, philosophical ethicists sometimes distinguish them, **using ethics to refer to theories and conceptual studies relating to good and evil and right and wrong**, and using morality and its related terms to refer to actual, real-world beliefs and practices concerning proper conduct.

fsfs-zh 中不少地方将此词译为“伦理”，而《现代汉语词典》（第6、7版）对“伦理”的解释是（个别字可能和原文有出入，词典不在手上）：“人与人相处的各种道德准则”。
按照《现代汉语词典》的解释，“伦理”其实范围应该是比“ethics”小的，并且对于软件自由方面的道德，我个人认为并不能说是“人与人之间的”。
所以，我建议“ethics”译成“道德”，这也包括其派生词。

**Comment by tonghuix** [comment]
如果尝试替换成“道义”，派生的时候就换着用“道义责任”？或者换成“品德”？

**Comment by tonghuix** [comment]
我明白你的意思，只是我觉得翻译成道德感觉又有点太大了，所以说也许道义稍微好一点。你觉得呢？
