### ISSUE TITLE
关于格式规范的一些疑问

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#243]
>- 中英文混排时，英文和中文之间留有空格，例如：推广 Free Software 的理念。若邻近标点符号则不需要空格，如：Free Software（自由软件）。
>- 除代码和特例（比如域名），所有标点符号均为全角

那么

1. 阿拉伯数字或链接和中文之间需不需要空格？
2. 在英文语境下，是否需要使用全角的括号、冒号？

**Comment by tonghuix** [comment]
1. 这是需要有空格的，阿拉伯数字很多时候是和英文一样处理的

2. 一般来说括号的处理是和括号里的字符相关的，例子：

```
自由软件 (Free Software) —— 英文括号，两边加空格
Free Software（自由软件）—— 中文全角空格
```

这个处理一般是 UI 翻译的时候遵循的，但是在文档和涉及到可能印刷的时候就需要一些变通，比如有的机构或出版社有统一规定。另外这里给一个知乎的讨论：https://www.zhihu.com/question/20488833

**Comment by tonghuix** [comment]
我还查到一个国际翻译项目指南，这竟然是 ISO 的一个标准：https://wenku.baidu.com/view/8f86deeb6edb6f1afe001fab.html?re=view

**Comment by Hagb** [comment]
@tonghuix 关于第1点，是否是全部时候？
比如附录C，

> 这首歌是7/8拍的；这种不寻常的不均匀古怪节奏常常被看成是一种错误。该部分可拆分为三个单拍子，以慢—快—快或3—2—2拍子划分。保加利亚音乐的这种节奏，经常可以拉长，有些音乐家分析这首歌曲可以替代为3—2—3拍子；然而，最后的3拍并不如第一个3拍那么长。搜集并教授这种舞蹈的伊夫·莫罗，倾向于7拍节奏。

是不是该改为

> 这首歌是 7/8 拍的；这种不寻常的不均匀古怪节奏常常被看成是一种错误。该部分可拆分为三个单拍子，以慢—快—快或 3—2—2 拍子划分。保加利亚音乐的这种节奏，经常可以拉长，有些音乐家分析这首歌曲可以替代为 3—2—3 拍子；然而，最后的 3 拍并不如第一个 3 拍那么长。搜集并教授这种舞蹈的伊夫·莫罗，倾向于 7 拍节奏。

**Comment by tonghuix** [comment]
理论上说现代排版系统软件（比如 LibreOffice 等）已经可以自动处理阿拉伯数字的空格问题，但是网页显示以及绝大多数 UI 界面设计还没有能够如此，因此依旧需要空格。另外我记得生成的 PDF 里这个附录 C 的阿拉伯数字的空格好像也自动出现了。

我手贱把早先生成的 PDF 删了，因为现在一直没能成功生成 PDF 所以没法核实。

**Comment by Hagb** [comment]
PDF 里是有空格的。好像阿拉伯数字和中文之间都自动加上了中文。
（话说没成功生成 PDF 什么情况……）

**Comment by tonghuix** [comment]
#242 发现的这个问题，现在用 #244 在考虑解决

全角括号不应该有空格，我记得关于引号是不能参考括号的。只要是中文环境，哪怕是括起来的都是英文也要用中文引号，除非段落里都是英文，括起来的也是英文。例如：

```
自由软件的英文是“Free Software”，免费软件的英文是"Freeware" 
What make 'Free Software' is different from‘Open Source’…
```
 这个例子混用了中英文引号，可以看出明显美感的差异
