### ISSUE TITLE
《政府推动自由软件的措施》一处问题

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#253]
> **largely state-funded** activities such as charter schools
> **大型国有**活动比如特许公立学校

此处 largely 应是副词吧？修饰 state-funded ，表“主要由国家出资”的意思吧？

**Comment by tonghuix** [comment]
确实。这是一处翻译错误，主要由国家出资这个翻译是对的。

**Comment by IFRFSX** [comment]
@tonghuix 
@hagb 
大部分由国家出资    行不行？

**Comment by Hagb** [comment]
也可以的。大部分由国家出资的

于 2019年2月11日 GMT+08:00 下午6:23:14, IFRFSX <notifications@github.com> 写到:

**Comment by tonghuix** [comment]
@IFRFSX 当然也是可以的。
