### ISSUE TITLE
《自由与非自由软件的分类》（categories.md）中的图片最好给出中文版的地址

### ISSUE THREAD

**Issue by Hagb** [beijinglug/fsfs-zh#257]
如题。

还有就是，是把中文版图片放到 gnu.org 后添加 gnu.org 处的地址，还是添加 fsfs-zh 处的地址？

**Comment by tonghuix** [comment]
图片的上传确实是个麻烦事，我觉得最好能上传到 gnu.org，然后提换成 gnu.org 的地址

**Comment by Hagb** [comment]
> Github这边的图片 URL 就不要改了
emmm…是说 fsfs-zh 这边的添加 GitHub 的地址？还是说不变动？

**Comment by tonghuix** [comment]
这边其实是自动生成的 Github 的URL，不用改动即可。

**Comment by Hagb** [comment]
看起来我之前没说清楚…
那么现在是不是这样：
categories.md 中添加 GitHub 的中文版图片地址

**Comment by tonghuix** [comment]
我看到那个 PR 的改动了，明白你的意思了。

在想要不要把这个上传到 GNU 先，然后这边也用 GNU 的地址，这样中文版和英文版都在 GNU 官网地址是不是比较统一一些？

**Comment by Hagb** [comment]
gnu 那边，已经上传了，估计合并到 gnu.org 还要几个小时
到时候可以通过 <https://www.gnu.org/philosophy/category.zh-cn.svg> 来访问
