### ISSUE TITLE
有些 FSF 的版权声明缺失

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/fsfs-zh#278]
相比于之前 index.md 这个文件下面的版权声明，PDF 版少了一部分。目前来看是需要加到 template.tex 文件里的，当初不知道为啥忘记加进去了。

**Comment by Hagb** [comment]
具体是哪？
我能看到
![捕获4](https://user-images.githubusercontent.com/10961094/56077822-50882500-5e13-11e9-8311-04266501a43a.PNG)

**Comment by tonghuix** [comment]
@Hagb 那只是译本使用 GFDL 的声明，可以看 #280 我正在修正了。
