### ISSUE TITLE
"copyleft" was translated inappropriately to "共产" in the GPL License

### ISSUE THREAD

**Issue by biergaizi** [beijinglug/fsfs-zh#57]
> The GNU General Public License is a free, **copyleft** license for software and other kinds of works.

Was translated to

> GNU通用公共许可协议是一份面向软件及其他类型作品的，自由的版权**共产**协议。

In the whole license, the word "copyleft" only appears once, in the opening sentence for introduction, so there's little context for the translator for reference. The translator, 阮坤良, picked up a word "共产" for his own understanding for "copyleft".

I don't have any complain for HIS personal opinion. However, as a fsfs-zh translation Project, as a whole, translating "copyleft" to "共产" is misleading for readers, since RMS himself never uses "communism", in addition, it is only limited as a concept of copyright, not for all types of property. It is problematic and not acceptable.

I'm going to send a Pull Request to convert "共产" back to "Copyleft".

**Comment by tonghuix** [comment]
额，要不加一个注释？

**Comment by Artoria2e5** [comment]
“共产”可以说完全不对。 https://www.gnu.org/philosophy/shouldbefree.html#commuism

**Comment by persmule** [comment]
“左版”吧，我比较赞同这个译法。

**Comment by Artoria2e5** [comment]
理解“左版”需要读者把这东西联系到”左右“，然后把”右“联系到”权利“……

**Comment by persmule** [comment]
但你要知道RMS正有此意……


在 2016年09月12日 11:37, Mingye Wang 写道:

**Comment by Artoria2e5** [comment]
你这是在加智商壁垒，我的朋友……

**Comment by persmule** [comment]
那你说怎么办？或许留着不翻也是个选择……


在 2016年09月12日 11:44, Mingye Wang 写道:

**Comment by Artoria2e5** [comment]
我已經列出了很多翻譯選擇，也給出過推薦了。

**Comment by persmule** [comment]
那么“逆版权”也比“反版权”好，因为copyleft是“逆”用版权法的形式反对版权法的原本目的，而非直接“反”版权。


在 2016年09月12日 11:46, Mingye Wang 写道:

**Comment by tonghuix** [comment]
别争论了，推荐还是不翻译，这样可以避免很多争论

**Comment by nadebula** [comment]
To persmule:
根据美国宪法，版权法的初衷是好的（促进进步和公众福祉），但是被出版商阶级把经念歪了，参见我翻译的“对版权的错误解读”一文。专利法也一样（初衷是鼓励发表各种思想），只是其代价（赋予发表者垄断权）对于软件行业过于沉重。另外，我同意“左版”的译法；并且认为求同存异也是可以的。本来就是集体贡献的项目，不必强求所有人的翻译和理解都一样。

**Comment by tonghuix** [comment]
各位看这样解决如何，在此文首页加一个说明，只需要简单说copyleft咱们不认同他翻译为“共产”，但为了保证原文完整性，所以这里还是没改动

**Comment by persmule** [comment]
就改回copyleft有何不可？

**Comment by persmule** [comment]
要不就由我重新校对一下那篇文章，因为那个版本的问题可能还不小（如“码农”之类）。

**Comment by tonghuix** [comment]
好，这样也可以！所以基本就变成重新翻译了。。

**Comment by tonghuix** [comment]
换了一篇文章

**Comment by biergaizi** [comment]
你们可别折腾了！直接改回“copyleft”啊！

本 Issue 讨论的问题是这篇文章里的用词问题，不是 copyleft 该怎么翻译的问题，copyleft 的翻译问题远远比这篇文章的用词问题复杂的多。我的本意是保留所有的 copyleft，在翻译临近 release 的时候讨论一下该怎么翻译，然后直接 sed/awk 一下就行了。

如果要讨论 copyleft 的翻译问题请另开 issue，不要劫持讨论内容 (thread-hijacking) !
