### ISSUE TITLE
Part V: How to Choose a License for Your Own Work

### ISSUE THREAD

**Issue by mytbk** [beijinglug/fsfs-zh#61]
docs/license-recommendations.md
该文此前没人翻译过。计划在9月12日前完成。

**Comment by mytbk** [comment]
刚刚翻译完Introduction,可以在我的网站那里看看已经翻译好的部分：

https://vimacs.cnjabber.net/fsfs-zh/docs/license-recommendations

**Comment by tonghuix** [comment]
嘿嘿赞！

**Comment by mytbk** [comment]
翻译到Software->Libraries.
里面pushover software license不会翻译。

**Comment by tonghuix** [comment]
我认为是否可以翻译成，推翻软件许可证？

**Comment by mytbk** [comment]
pushover没有推翻的意思：
pushover UK: ['pʊʃəʊvə], US: ['pʊʃ'ovɚ]
  Word Explanation:
     * n. 易于征服或控制的人；容易打败的对手；容易做的事情

  Web Reference:
     * Pushover
       推覆分析; 易于征服或控制的人; 易做之事
     * Pushover analysis
       静力弹塑性分析; 推覆分析; 静力弹塑性分析
     * pushover分析
       push over analysis; Push-over analysis; pushover analysis

  Online Resource:
     * http://www.ldoceonline.com/search/?q=pushover

**Comment by mytbk** [comment]
已经翻译完

**Comment by tonghuix** [comment]
先提交PR吧，合并以后再修改
