### ISSUE TITLE
Part V:  On Selling Exceptions to the GNU GPL 

### ISSUE THREAD

**Issue by mytbk** [beijinglug/fsfs-zh#68]
这是FSF博客的一篇文章：
https://www.fsf.org/blogs/rms/selling-exceptions

长度不太长，但是考虑到下周开始我就比较忙了，因此计划翻译时间还是比较长，争取在9月18日之前完成。

**Comment by tonghuix** [comment]
注意翻译质量，若能在17号之前完成最好

**Comment by mytbk** [comment]
翻译到Qt和KDE那里。
https://vimacs.cnjabber.net/fsfs-zh/docs/selling-exceptions

**Comment by tonghuix** [comment]
有些话调整一下语序，个别的有点啰嗦

**Comment by mytbk** [comment]
翻译完了，之前的翻译还没调整。
