### ISSUE TITLE
校对进度

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/fsfs-zh#76]
粗体字的文章是重要文章，需要校对时重点留意，力图出精品。

- [x] Foreword to the Third Edition 
- [x] Foreword to the First Edition
- [x] Preface 
- Part I: The GNU Project and Free Software
   - [x]  **What Is Free Software?** 
   - [x] The GNU Project
   - [x] The Initial Announcement of the GNU Operating System 
   - [x] **Free Software Is Even More Important Now .**
   - [x] Why Schools Should Exclusively Use Free Software 
   - [x] Measures Governments Can Use to Promote Free Software
   - [x] **Why Free Software Needs Free Documentation**
   - [x] **Selling Free Software**
   - [x] **Free Hardware and Free Hardware Designs** 
   - [x] **Applying the Free Software Criteria** 
- Part II: What’s in a Name?
   - [x] What’s in a Name? .
   - [x] Linux and the GNU System
   - [x] **Categories of Free and Nonfree Software** 
   - [x] **Why Open Source Misses the Point of Free Software** 
   - [x] **Did You Say “Intellectual Property”? It’s a Seductive Mirage** 
   - [x] Why Call It the Swindle? 
   - [x] **Words to Avoid** (or Use with Care) Because They Are Loaded or Confusing
- Part III: Copyright and Injustice
   - [x] **The Right to Read**
   - [x] **Misinterpreting Copyright—A Series of Errors** 
   - [x] Science Must Push Copyright Aside
   - [x] **Copyright vs. Community in the Age of Computer Networks** 
- Part IV: Software Patents: Danger to Programmers
   - [x] **Software Patents and Literary Patents** 
   - [x] **The Danger of Software Patents** 
   - [x] Giving the Software Field Protection from Patents 
- Part V: Free Software Licensing
   - [x] **Introduction to the Licenses** 
   - [x] **How to Choose a License for Your Own Work**
   - [x] The X Window System Trap 
   - [x] **Programs Must Not Limit the Freedom to Run Them**
   - [x] **What Is Copyleft?** 
   - [x] **Why Copyleft?**
   - [x] **Copyleft: Pragmatic Idealism**
   - [x] The GNU General Public License
   - [x] **Why Upgrade to GPLv3**
   - [x] The GNU Lesser General Public License
   - [x] GNU Free Documentation License 
   - [x] On Selling Exceptions to the GNU GPL
- Part VI: Traps and Challenges
   - [x] **Can You Trust Your Computer? .**
   - [x] **The JavaScript Trap**
   - [x] Releasing Free Software If You Work at a University 
   - [x] Nonfree DRM’d Games on GNU/Linux: Good or Bad? 
   - [x] **The Danger of E-Books** 
   - [x] **E-books Must Increase Our Freedom, Not Decrease It** 
   - [x] **Who Does That Server Really Serve?** 
- Part VII: Value Community and Your Freedom
   - [x] **Avoiding Ruinous Compromises** 
   - [x] Overcoming Social Inertia 
   - [x] **Freedom or Power?**
   - [x] Imperfection Is Not the Same as Oppression 
   - [x] **How Much Surveillance Can Democracy Withstand?** 
- Appendix 
  - [x] A: Note on Software 
  - [x] B: Translations of “Free Software” and “Gratis Software”
  - [x] C: The Free Software Song

**Comment by liushuyu** [comment]
```
In article javascript-trap.md: 30:
很多用户注意到这一准则同样适用于浏览器提供安装的插件，由于它们可以是自由或非自由的。
                               ^~~~~
error: `提供安装的' produced confusing meaning
note: Better change to `上安装的'

In article javascript-trap.md: 30:
很多用户注意到这一准则同样适用于浏览器提供安装的插件，由于它们可以是自由或非自由的。
^
warning: The result clause placed before the reason clause, which is not common in Chinese grammar.
note: Promote the part after the comma to the front.

In article javascript-trap.md: 136:
我们试着提出了一种策略，这种策略认为一段 JavaScript 程序是非平凡的，如果：
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: non-Chinese style expression
note: `我们试着提出一种策略，如果一段 JavaScript 程序满足以下标准的任何一点，它就是非平凡的：`
```

**Comment by liushuyu** [comment]
General problem:
In some articles, the term `Tivoization` is translated into `TiVo 化`, while in some other articles, it is translated into `机顶盒化`. 
The consistency matters, I recommend to consider a uniformed translation for `Tivoization`.

**Comment by persmule** [comment]
乍看之下TiVo 化好一些，因为别的机顶盒厂家不一定会这么干。

**Comment by liushuyu** [comment]
>乍看之下TiVo 化好一些，因为别的机顶盒厂家不一定会这么干。

Seems like you got some good points, and `TiVo 化` is a direct translation to Chinese.
And it should be noted that some bg information would be needed to clarify the mean of `TiVo`.

**Comment by persmule** [comment]
在《rms-why-gplv3》一文中有对Tivoization的解释。

**Comment by liushuyu** [comment]
>在《rms-why-gplv3》一文中有对Tivoization的解释。

Which has been translated by @biergaizi and used `机顶盒化` as translation
