### ISSUE TITLE
docs/fs-translations/zh*: 用 Source Han Sans 重做

### ISSUE THREAD

**Issue by Artoria2e5** [beijinglug/fsfs-zh#78]
文泉驿系列——尤其是大部分手动拖拽的正黑——最怕的就是把一个个字放大了拿出来看了……

**Comment by tonghuix** [comment]
貌似就是用的 Source Han Sans 吧

**Comment by Artoria2e5** [comment]
> 保持原文风格

这站不住脚啊……Orz

**Comment by tonghuix** [comment]
为啥站不住脚？

**Comment by Artoria2e5** [comment]
历史局限性、还有我们更懂中文。

**Comment by tonghuix** [comment]
这是小细节，与其关注这些，不如帮忙多校对几篇文章去

**Comment by Artoria2e5** [comment]
小细节引用次数够多就够了……

**Comment by tonghuix** [comment]
幸亏引用次数不多

**Comment by biergaizi** [comment]
@tonghuix 什么叫“原文”自带的？在正确排版的文章中，样式不属于内容。除非原文是某种历史出版物，保留原稿的排版样式具有意义之外；保留几行样式代码 tag 何用之有，况且还降低文字可读性也不利于传播思想啊？

**Comment by biergaizi** [comment]
> 这是小细节，与其关注这些，不如帮忙多校对几篇文章去

这种说法对项目也非常有害，同理，很多项目中，也有同样的做法：

> 这个按钮位置不对，这是小细节，与其关注这个，不如去完善标准库

从而导致很多小问题多少年都解决不了。对于这种细节问题，妥当的做法是：

> 这种细节我们开发者不打算管，但对于有时间和兴趣者，欢迎 Patch.

**Comment by tonghuix** [comment]
@biergaizi  源文件就是已经矢量化的PDF文件，我就直接给导出png文件以方便嵌入markdown而已。为此没必要重新制作。

**Comment by tonghuix** [comment]
@biergaizi @Artoria2e5  这里下载源文件，文章部分是texinfo的。http://www.gnu.org/doc/fsfs3-hardcover.tar.gz

**Comment by Artoria2e5** [comment]
好的，有空我看看。

**Comment by Artoria2e5** [comment]
[svg.7z.zip](https://github.com/beijinglug/fsfs-zh/files/493832/svg.7z.zip)
![zh-cn-free](https://cloud.githubusercontent.com/assets/6459309/18846572/a0d9f87c-83f4-11e6-85e6-5389dcec67ff.png)
![zh-cn-gratis](https://cloud.githubusercontent.com/assets/6459309/18846573/a0de52aa-83f4-11e6-96e6-af5acd450e01.png)
![zh-cn-libre](https://cloud.githubusercontent.com/assets/6459309/18846577/a0e780a0-83f4-11e6-9dde-158dcbcbfa7c.png)
![zh-tw-free](https://cloud.githubusercontent.com/assets/6459309/18846575/a0e25e2c-83f4-11e6-8335-0d2ec996650b.png)
![zh-tw-gratis](https://cloud.githubusercontent.com/assets/6459309/18846574/a0e1090a-83f4-11e6-8123-1c068c728aef.png)
![zh-tw-libre](https://cloud.githubusercontent.com/assets/6459309/18846576/a0e3909e-83f4-11e6-85ca-7268a2beef14.png)

**Comment by tonghuix** [comment]
要不你直接PR？
