### ISSUE TITLE
校对流程应该保留 anchor ID 标记

### ISSUE THREAD

**Issue by Artoria2e5** [beijinglug/fsfs-zh#80]
> 文中所有不相关的 Texinfo 和 HTML 代码符号都可以删掉。

Anchor ID 之类的标记有助于提供对文章章节引用的能力，保留原文的 anchor 则可以简化章节对应的流程。

**Comment by tonghuix** [comment]
anchor 可以保留，但需要调整为markdown格式，输入pdf的时候还要调整到latex格式，太麻烦了，干脆不要了

**Comment by tonghuix** [comment]
咱们有时间要解决一下这个问题。

先解决技术问题，搞定了一篇，其他的可以一边校对一边加上。

**Comment by tonghuix** [comment]
看这个，可以看看 https://github.com/jgm/pandoc/issues/1299

**Comment by tonghuix** [comment]
解决这个问题开了一个新分支 issue-80，@Hagb 已经搞定了一些，至少是能作出一些改变了。也许需要更加优雅，或者更加自动化的办法。

**Comment by tonghuix** [comment]
目前来看分支 issue-80 已经解决了这个问题，我打算稍后合并到 master 并开新的 release —— 2019.2！
