### ISSUE TITLE
fsfs3-paperback-cover-art.svg 里面的照片用 png 好像有点太大了……

### ISSUE THREAD

**Issue by Artoria2e5** [beijinglug/fsfs-zh#83]
GitHub 网页打开能卡浏览器……

做了个 jpg (Q90, progressive, float, 4:4:4, smooth 0.30) 替换，虽然还是很大：

[fsfs3-paperback-cover-art.zip](https://github.com/beijinglug/fsfs-zh/files/466259/fsfs3-paperback-cover-art.zip) // [rms](https://cloud.githubusercontent.com/assets/6459309/18420859/a91dceec-784a-11e6-91df-88fc5fad4c05.jpg)

**Comment by tonghuix** [comment]
用的是原文件默认的svg，只是汉化了里面的内容而以
